import {cpSync,existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
if(process.platform!=='darwin') throw new Error('The native preview package requires macOS.');
if(!existsSync(path.join(root,'dist/main/index.cjs'))) throw new Error('Build Agent Mode before packaging.');
const electron=createRequire(import.meta.url)('electron');
const app=path.join(root,'release/Muster Agent Preview.app');
mkdirSync(path.dirname(app),{recursive:true});
execFileSync('ditto',[path.resolve(electron,'../../..'),app]);
const plist=path.join(app,'Contents/Info.plist');
for(const [key,value] of Object.entries({CFBundleIdentifier:'dev.themuster.agent.preview',CFBundleName:'Muster Agent',CFBundleDisplayName:'Muster Agent',CFBundleShortVersionString:'0.2.0'})) execFileSync('/usr/libexec/PlistBuddy',['-c',`Set :${key} ${value}`,plist]);
const resources=path.join(app,'Contents/Resources/app');mkdirSync(resources,{recursive:true});
cpSync(path.join(root,'dist'),path.join(resources,'dist'),{recursive:true});
writeFileSync(path.join(resources,'package.json'),JSON.stringify({name:'muster-agent',productName:'Muster Agent',version:'0.2.0',main:'dist/main/index.cjs'}));
execFileSync('codesign',['--force','--deep','--sign','-',app],{stdio:'pipe'});
console.log(app);
