import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
const require=createRequire(import.meta.url);
const {parseHTML}=require('linkedom');
const {window}=parseHTML('<html><body><div id="root"></div></body></html>');
Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,CustomEvent:window.CustomEvent,localStorage:{getItem(){return null},setItem(){}},requestAnimationFrame:(cb:any)=>setTimeout(cb,0),cancelAnimationFrame:clearTimeout});
(window.HTMLElement.prototype as any).attachEvent=function(){};(window.HTMLElement.prototype as any).detachEvent=function(){};
const calls:{command:string;input:any}[]=[];
let stored:any=null;
window.muster={subscribe(){return()=>{}},async invoke(command:string,input:any){calls.push({command,input});
  if(command==='providers.list')return [{id:'hybrow',name:'Hybrow',available:true,status:'ready',identityMasked:'',models:[{id:'m',name:'Model M'},{id:'f',name:'Model F'}]}];
  if(command==='settings.folderModel.get')return {value:stored};
  if(command==='settings.folderModel.set'){stored=input.value;return {value:stored};}
  if(command==='chat.defaults')return stored?{providerId:'hybrow',model:stored.model,source:'folder'}:{providerId:'hybrow',model:'m',source:'user'};
}} as any;
const React=await import('react');
const {createRoot}=await import('react-dom/client');
const store=await import('../src/renderer/store');
const {FolderDefaultModelSheet,requestFolderDefaultModel,DEFAULT_SOURCE_LABEL}=await import('../src/renderer/components/settings/FolderDefaultModelSheet');
(store as any).applySnapshot?.({folders:[{id:'f1',name:'Repo',path:'/r'}],chats:[],projects:[]});
if(!store.getState().snapshot)Object.assign(store.getState(),{snapshot:{folders:[{id:'f1',name:'Repo',path:'/r'}],chats:[],projects:[]}});
const errors:unknown[]=[];
const root=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
root.render(<FolderDefaultModelSheet/>);await delay(20);
assert.equal(document.querySelector('[data-testid="folder-default-model"]'),null,'nothing renders until a folder asks');
requestFolderDefaultModel('f1');await delay(60);
assert.deepEqual(errors,[]);
const text=()=>document.body.textContent??'';
assert.match(text(),/Default model for “Repo”/);
assert.match(text(),/Inherited from your default/);
assert.match(text(),new RegExp(`start with m · ${DEFAULT_SOURCE_LABEL.user}`));
assert.ok(calls.some(call=>call.command==='settings.folderModel.get'&&call.input.folderId==='f1'));
// Choose "Model F" in the picker.
(document.querySelector('.folder-default-model-row button') as HTMLButtonElement).click();await delay(30);
const option=Array.from(document.querySelectorAll('[role="option"]')).find(node=>/Model F/.test(node.textContent??'')) as HTMLElement|undefined;
assert.ok(option,'the picker lists ready models');
option!.click();await delay(60);
assert.deepEqual(calls.filter(call=>call.command==='settings.folderModel.set').at(-1)?.input.value?.model,'f');
assert.match(text(),/Folder override/);
assert.match(text(),/start with f · From this folder’s default/);
(Array.from(document.querySelectorAll('button')).find(node=>node.textContent==='Reset to inherited') as HTMLButtonElement).click();await delay(60);
assert.equal(calls.filter(call=>call.command==='settings.folderModel.set').at(-1)?.input.value,null);
assert.match(text(),/Inherited from your default/);
root.unmount();
console.log('Folder default model sheet passed: opens on request, provenance, set and reset.');
