import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require = createRequire(import.meta.url);
const {parseHTML} = require('linkedom');
const {window} = parseHTML('<html><body><div id="root"></div></body></html>');
Object.assign(globalThis, {window, document:window.document, HTMLElement:window.HTMLElement, IS_REACT_ACT_ENVIRONMENT:true});
const React = await import('react');
const {act} = React;
const {createRoot} = await import('react-dom/client');
const {HindsightPanel} = await import('../src/renderer/components/HindsightPanel');
const root = createRoot(document.getElementById('root')!);
const calls: {command:string;folderId:string}[] = [];
let verified = false;
let fail = false;
let pending: ReturnType<typeof Promise.withResolvers<{bankId:string;results:{id:string;text:string}[]}>> | undefined;
window.muster = {subscribe:()=>()=>{},invoke:async (command:string,input:{folderId:string}) => {
  calls.push({command,folderId:input.folderId});
  if (command === 'hindsight.status') return {configured:true,revision:1,bankId:`bank-${input.folderId}`,connection:fail?'failed':verified?'verified':'unchecked',...(fail?{connectionError:'The last request failed. Retry when ready.'}:{})};
  if (command === 'hindsight.recall') {
    if (pending) return pending.promise;
    if (fail) throw new Error('Service unavailable');
    verified=true; return {bankId:`bank-${input.folderId}`,results:[{id:'one',text:'synthetic recalled memory'}]};
  }
  throw new Error(`Unexpected command: ${command}`);
}};
const text = () => document.querySelector('.hindsight-panel')!.textContent!;
const submit = () => document.querySelector('form')!.dispatchEvent(new window.Event('submit',{bubbles:true,cancelable:true}));
await act(async()=>{root.render(<HindsightPanel folderId="first"/>);});
assert.match(text(),/Configured · connection not verified/);
assert.deepEqual(calls.map(call=>call.command),['hindsight.status'],'mount sends no hidden memory probe');
await act(async()=>{submit();});
assert.match(text(),/Connection verified by last request/);
assert.match(text(),/synthetic recalled memory/);
fail=true;
await act(async()=>{submit();});
assert.match(text(),/Configured · last request failed/);
assert.match(text(),/Service unavailable/);
assert.equal(document.querySelector('textarea')!.hasAttribute('disabled'),false,'failure leaves retry input available');
fail=false; verified=false;
pending=Promise.withResolvers();
await act(async()=>{submit();});
assert.match(text(),/Waiting for Hindsight/);
await act(async()=>{root.render(<HindsightPanel folderId="second"/>);});
assert.match(text(),/bank-second/);
assert.doesNotMatch(text(),/Waiting for Hindsight|synthetic recalled memory/);
await act(async()=>{pending!.resolve({bankId:'bank-first',results:[{id:'late',text:'private result from previous scope'}]});});
assert.doesNotMatch(text(),/private result from previous scope|Connection verified/);
assert.equal(calls.filter(call=>call.command==='hindsight.recall').length,3);
await act(async()=>{root.unmount();});
console.log('Hindsight panel lifecycle passed: no hidden probe, real-operation status, retry, stale scope suppression.');
