import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
const require=createRequire(import.meta.url);
const {parseHTML}=require('linkedom');
const {window}=parseHTML('<html><body><div id="root"></div></body></html>');
Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,localStorage:{getItem(){return null},setItem(){}},requestAnimationFrame:(cb:any)=>setTimeout(cb,0),cancelAnimationFrame:clearTimeout});
(window.HTMLElement.prototype as any).attachEvent=function(){};(window.HTMLElement.prototype as any).detachEvent=function(){};
const calls:{command:string;input:any}[]=[];
let enabled=true;const excluded=new Map<string,any>();
const notes=[{id:'a',text:'Deploys use staging first',source:'local',scope:'Repo'},{id:'b',text:'Run pnpm, not npm',source:'local',scope:'Repo'}];
window.muster={subscribe(){return()=>{}},async invoke(command:string,input:any){calls.push({command,input});
  if(command==='memory.recall.preview')return {enabled,engine:true,records:input.prompt.trim()?notes.filter(n=>!excluded.has(n.id)):[],excluded:[...excluded.values()]};
  if(command==='memory.recall.exclude'){if(input.excluded)excluded.set(input.id,{id:input.id,text:input.text,source:'local',scope:''});else excluded.delete(input.id);return {excluded:[...excluded.values()]};}
}} as any;
const React=await import('react');
const {createRoot}=await import('react-dom/client');
const {MemoryRecallChip}=await import('../src/renderer/components/MemoryRecallChip');
const errors:unknown[]=[];
const root=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
const chip=()=>document.querySelector('[data-testid="memory-recall-chip"]') as HTMLButtonElement|null;
root.render(<MemoryRecallChip chatId="c1" text=""/>);await delay(30);
assert.equal(chip(),null,'an empty draft with nothing removed shows no chip');
root.render(<MemoryRecallChip chatId="c1" text="deploy it"/>);await delay(100);
assert.equal(calls.filter(call=>call.command==='memory.recall.preview'&&call.input.prompt==='deploy it').length,0,'typing is debounced');
await delay(500);
assert.deepEqual(errors,[]);
assert.equal(chip()?.textContent,'2 memories');
chip()!.click();await delay(20);
const text=()=>document.body.textContent??'';
assert.match(text(),/Recalled for the next turn/);
assert.match(text(),/Deploys use staging first/);
assert.match(text(),/memory engine adds its own matches/);
(document.querySelector('[aria-label^="Leave out: Deploys"]') as HTMLButtonElement).click();await delay(80);
assert.deepEqual(calls.find(call=>call.command==='memory.recall.exclude')?.input,{chatId:'c1',id:'a',text:'Deploys use staging first',excluded:true});
assert.equal(chip()?.textContent,'1 memory');
assert.match(text(),/Left out in this chat/);
(document.querySelector('[aria-label^="Restore: Deploys"]') as HTMLButtonElement).click();await delay(80);
assert.equal(chip()?.textContent,'2 memories');
// Escape closes the popover; turning auto-recall off hides the chip.
{const event=new window.Event('keydown',{bubbles:true});Object.assign(event,{key:'Escape'});document.dispatchEvent(event);}await delay(20);
assert.equal(chip()?.getAttribute('aria-expanded'),'false');
enabled=false;root.render(<MemoryRecallChip chatId="c1" text="deploy it now"/>);await delay(600);
assert.equal(chip(),null);
root.unmount();
console.log('Memory recall chip passed: debounced preview, inspect, leave out, restore, disabled state.');
