import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
const require=createRequire(import.meta.url),{parseHTML}=require('linkedom');
const {window}=parseHTML('<html><body><div id="root"></div></body></html>');
Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node});
const calls:string[]=[];let resolve!:()=>void,reject!:(reason:Error)=>void;
window.muster={invoke(command:string,input:{text:string}){assert.equal(command,'clipboard.write');calls.push(input.text);return new Promise<void>((yes,no)=>{resolve=yes;reject=no;});}};
const React=await import('react'),{createRoot}=await import('react-dom/client');
const {MessageMeta}=await import('../src/renderer/components/MessageMeta');
const root=createRoot(document.getElementById('root')!);
root.render(<MessageMeta text={'## Exact markdown\n\n| A | B |'} createdAt="2026-09-19T18:19:00.000Z"/>);await delay(15);
const button=document.querySelector('button')!;button.click();button.click();await delay(5);
assert.equal(calls.length,1);assert.equal(calls[0],'## Exact markdown\n\n| A | B |');
assert.equal(document.querySelector('time')!.getAttribute('dateTime')??document.querySelector('time')!.getAttribute('datetime'),'2026-09-19T18:19:00.000Z');
assert.match(document.querySelector('time')!.getAttribute('title')!,/2026/);
resolve();await delay(10);assert.match(document.querySelector('[role="status"]')!.textContent!,/Copied/);
button.click();await delay(5);reject(new Error('clipboard unavailable'));await delay(10);
assert.match(document.querySelector('[role="status"]')!.textContent!,/Could not copy/);
root.render(<MessageMeta text="later" createdAt="invalid"/>);await delay(10);assert.equal(document.querySelector('time'),null);
root.unmount();console.log('Message copy preserves text, deduplicates pending clicks, reports success/failure, and uses actual valid timestamps.');
