/** Run with node tests/run-sidebar-navigation.mjs; dynamic chunks initialize UI after the DOM. */
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {setTimeout as delay} from 'node:timers/promises';
const require=createRequire(import.meta.url),{parseHTML}=require('linkedom');
const {window}=parseHTML('<html><body><div id="root"></div></body></html>');
const saved=new Map<string,string>(),scrolls:string[]=[];
Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,MutationObserver:window.MutationObserver,ResizeObserver:class{observe(){}disconnect(){}},requestAnimationFrame:(fn:any)=>setTimeout(fn,0),cancelAnimationFrame:clearTimeout,localStorage:{getItem:(key:string)=>saved.get(key)??null,setItem:(key:string,value:string)=>saved.set(key,value)}});
const styles=()=>({getPropertyValue:()=>'',direction:'ltr',position:'static',overflow:'visible',overflowX:'visible',overflowY:'visible',display:'block',animationName:'none',transitionProperty:'none',transitionDuration:'0s',animationDuration:'0s',paddingTop:'0px',paddingBottom:'0px',paddingLeft:'0px',paddingRight:'0px'});
Object.assign(globalThis,{getComputedStyle:styles});window.getComputedStyle=styles;
window.HTMLElement.prototype.getBoundingClientRect=()=>({x:0,y:0,width:224,height:30,left:0,top:0,right:224,bottom:30});
window.HTMLElement.prototype.getClientRects=function(){return [this.getBoundingClientRect()];};
window.HTMLElement.prototype.scrollIntoView=function(){scrolls.push(this.dataset.chatId);};
window.KeyboardEvent=class extends window.Event {};
window.MouseEvent=class extends window.Event {};
window.PointerEvent=class extends window.MouseEvent {};
let focused:Element|null=null;
Object.defineProperty(document,'activeElement',{get:()=>focused??document.body});
window.HTMLElement.prototype.focus=function(){focused=this;};
window.HTMLElement.prototype.blur=function(){focused=null;};
const React=await import('react'),{createRoot}=await import('react-dom/client');
const {PendingAttentionControl}=await import('../src/renderer/components/PendingAttention');
const errors:unknown[]=[],opened:string[]=[];
const root=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
const attention={totalRequests:2,chats:[{chatId:'inactive',chatTitle:'Inactive task',approvalCount:1,questionCount:1,requests:[{itemId:'approval-1',kind:'approval' as const,createdAt:'now',sourceLabel:'Provider approval' as const},{itemId:'question-1',kind:'question' as const,createdAt:'now',sourceLabel:'Provider question' as const}]}]};
root.render(<PendingAttentionControl attention={attention} onOpenTask={id=>opened.push(id)}/>);await delay(40);
const trigger=document.querySelector('[aria-label="2 requests need input"]') as HTMLButtonElement;assert.ok(trigger);
assert.equal(document.querySelector('[data-native-preview-overlay]'),null,'requests are not an always-visible inline list');
trigger.focus();trigger.click();await delay(60);assert.deepEqual(errors,[]);
assert.ok(document.querySelector('[data-native-preview-overlay]'));
const destination=document.querySelector('[aria-label="Open task Inactive task: 1 approval · 1 question"]') as HTMLButtonElement;assert.ok(destination);
assert.equal(document.querySelector('input,textarea'),null,'global attention never answers a request');
const escape=new window.KeyboardEvent('keydown',{bubbles:true,cancelable:true});Object.assign(escape,{key:'Escape',code:'Escape'});destination.dispatchEvent(escape);await delay(50);
assert.equal(trigger.getAttribute('aria-expanded'),'false');assert.equal(document.activeElement,trigger,'Escape restores trigger focus');
trigger.click();await delay(50);(document.querySelector('[aria-label="Open task Inactive task: 1 approval · 1 question"]') as HTMLButtonElement).click();await delay(40);
assert.deepEqual(opened,['inactive']);assert.equal(trigger.getAttribute('aria-expanded'),'false');
root.render(<PendingAttentionControl attention={{totalRequests:0,chats:[]}} onOpenTask={()=>{}}/>);await delay(20);
assert.equal(document.querySelector('.pending-attention-trigger'),null);root.unmount();assert.deepEqual(errors,[]);
console.log('PASS: compact attention popup, source navigation, Escape focus restoration and zero-state removal');
