import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { setTimeout as delay } from 'node:timers/promises';
const require = createRequire(import.meta.url);
const {parseHTML} = require('linkedom');
const {window} = parseHTML('<html><body><div id="root"></div></body></html>');
window.innerWidth=1280;
window.innerHeight=840;
const persisted = new Map<string,string>();
Object.assign(globalThis,{window, document:window.document, HTMLElement:window.HTMLElement, Element:window.Element, localStorage:{getItem(key:string){return persisted.get(key)??null},setItem(key:string,value:string){persisted.set(key,value)}},requestAnimationFrame:(cb:any)=>setTimeout(cb,0),cancelAnimationFrame:clearTimeout, ResizeObserver:class {observe(){}unobserve(){}disconnect(){}}});
Object.assign(globalThis,{MutationObserver:window.MutationObserver});
Object.assign(globalThis, { getComputedStyle: () => ({ minHeight: '26px', maxHeight: '200px', borderTopWidth: '0px', borderBottomWidth: '0px', lineHeight: '20px', paddingTop: '3px', paddingBottom: '3px' }) });
Object.defineProperty(window.HTMLElement.prototype,'scrollHeight',{get(){return 800}});
Object.defineProperty(window.HTMLElement.prototype,'clientHeight',{get(){return 500}});
Object.defineProperty(window.HTMLElement.prototype,'offsetHeight',{get(){return 70}});
Object.defineProperty(window.HTMLElement.prototype,'offsetWidth',{get(){return 800}});
window.HTMLElement.prototype.getBoundingClientRect=()=>({height:500,width:800,top:0,left:0,bottom:500,right:800});
window.HTMLElement.prototype.getClientRects=()=>[];
window.HTMLElement.prototype.scrollTo=function({top}:any){this.scrollTop=top};
const chats=['a','b'].map(id=>({id,folderId:id==='a'?'folder-a':'folder-b',projectId:id==='a'?'project-a':'project-b',title:id,pinned:false,archived:false,draft:'',status:'completed',updatedAt:'',model:'test',mode:'agent'}));
const eventListeners = new Set<(event:any)=>void>();
const emit = (event:any) => { for (const listener of eventListeners) listener(event); };
let fileVersion = 1;
let releasePendingDiff: ((value:any)=>void) | undefined;
const nativePreviewCalls: Array<{command:string;input:any}> = [];
const documentText = '# Document preview\n\n| Feature | State |\n| --- | --- |\n| Links | Ready |\n\n<script>alert(1)</script>\n\n![External](https://example.invalid/private.png)';
window.muster={subscribe(listener:any){eventListeners.add(listener);return()=>eventListeners.delete(listener)},async invoke(c:string,p:any){if(c==='processes.summary')return {revision:1,sessions:[]};if(c==='files.nativeAvailable')return true;if(c==='files.nativeShow'||c==='files.nativePosition'||c==='files.nativeHide'){nativePreviewCalls.push({command:c,input:p});return;}if(c==='files.annotations.list')return [];if(c==='files.workbook')return {revision:'one',limited:false,sheets:[{name:'Summary',rows:[['Name','Amount','Status'],['Alpha','$1,200.50','Ready'],['Beta','0.00','Review']],formulas:{},limited:false}]};if(c==='git.diff'&&p.path==='src/pending.ts')return await new Promise(resolve=>{releasePendingDiff=resolve;});if(c==='git.diff')return {path:p.path,before:'before',after:'after',truncated:false};if(c==='files.read')return {path:p.path,text:p.path==='guide.md'?documentText:p.path==='large.md'?'x'.repeat(70000):p.path==='data.json'?JSON.stringify({nested:{answer:42}}):p.path==='invalid.json'?'{broken':p.path==='table.csv'?'Name,Note\nAlpha,Ready':p.path==='src/main.ts'?'export const total = 2;\nexport const ready = true;\n':'Version '+fileVersion,truncated:false};if(c==='workspace.watch')return; if(c==='app.snapshot')return {chats,folders:[],projects:[],version:1,activeChatId:'a'};if(c==='chat.timeline')return {items:[{id:p.id+'1',chatId:p.id,kind:'assistant',text:p.id==='a'?'Chat a updated `src/math.js`.\n\nBefore:\n```text\nexport function add(a, b) { return a + b; }\n```':'Chat '+p.id,createdAt:''}],revision:1};}};
const React=await import('react');
const {createRoot}=await import('react-dom/client');
const {App}=await import('../src/renderer/App');
const store=await import('../src/renderer/store');
const errors: unknown[] = [];
const root=createRoot(document.getElementById('root')!, {onUncaughtError:error=>errors.push(error)});root.render(<React.StrictMode><App/></React.StrictMode>);await store.boot();
for(const id of ['a','b','a','b','a']){await store.selectChat(id);for(let attempt=0;attempt<40&&!document.querySelector('.timeline')?.textContent?.includes('Chat '+id);attempt++)await delay(25);assert.equal(document.querySelectorAll('.timeline').length,1, 'exactly one mounted transcript after selecting '+id);assert.equal(document.querySelectorAll('.composer').length,1);assert.deepEqual(errors,[]);assert.match(document.querySelector('.timeline')!.textContent!,new RegExp('Chat '+id),JSON.stringify({timeline:store.getState().timelines[id],html:document.querySelector('.timeline')!.innerHTML}));assert.doesNotMatch(document.querySelector('.timeline')!.textContent!,new RegExp('Chat '+(id==='a'?'b':'a')));assert.deepEqual(errors,[]);}
assert.equal(document.querySelector('.md-code-lang')?.textContent,'JavaScript','generic code blocks near an edited path use that file extension’s syntax highlighter (shown by its display name)');
const streamingNode = document.querySelector('.timeline');
emit({type:'timelinePatch',chatId:'a',patch:{after:1,revision:2,items:[{id:'a1',chatId:'a',kind:'assistant',text:'Chat a live update',createdAt:''}]}});
await delay(60);
assert.equal(document.querySelector('.timeline'),streamingNode,'delta does not remount the transcript');
assert.match(streamingNode!.textContent!,/Chat a live update/);
emit({type:'timelinePatch',chatId:'a',patch:{after:0,revision:1,items:[{id:'a1',chatId:'a',kind:'assistant',text:'obsolete',createdAt:''}]}});
await delay(30);
assert.match(streamingNode!.textContent!,/Chat a live update/,'stale delta cannot rewind visible prose');
await store.openFile('folder','example.ts');
await new Promise(r=>setTimeout(r,80));
assert.match(document.querySelector('.file-view')!.textContent!,/Version 1/);
fileVersion=2;emit({type:'workspaceChanged',folderId:'folder'});
await new Promise(r=>setTimeout(r,80));
assert.match(document.querySelector('.file-view')!.textContent!,/Version 2/);
assert.equal(store.getState().activeChatId,'a','resource refresh must not switch chats');
assert.equal(document.querySelectorAll('.timeline').length,1);
// Markdown document views reuse the safe renderer and preserve source navigation.
await store.openFile('folder','guide.md'); await delay(80);
assert.ok(document.querySelector('.file-markdown h1'));
assert.ok(document.querySelector('.file-markdown table'));
assert.equal(document.querySelectorAll('.file-markdown script, .file-markdown img').length,0,'documents never execute HTML or fetch external images');
const sourceButton=Array.from(document.querySelectorAll<HTMLButtonElement>('.file-view-switch button')).find(el=>el.textContent==='View source')!;
sourceButton.click(); await delay(30);
assert.equal(document.querySelector('.file-markdown'),null);
assert.match(document.querySelector('.code-table')!.textContent!,/# Document preview/);
store.closeTab(store.getState().activeTabId!);
await store.openFile('folder','large.md'); await delay(80);
assert.equal(document.querySelector('.file-markdown'),null,'large Markdown does not get parsed into an unbounded AST');
assert.ok(document.querySelector('.file-view-switch button[disabled]'));
store.closeTab(store.getState().activeTabId!);
await store.openFile('folder','data.json'); await delay(60);
assert.ok(document.querySelector('.code-table'),'JSON opens as highlighted source by default');
Array.from(document.querySelectorAll<HTMLButtonElement>('.file-view-switch button')).find(el=>el.textContent==='View tree')!.click(); await delay(30);
assert.ok(document.querySelector('[aria-label="JSON structure"]'),'the JSON tree is an opt-in view');
const nested=Array.from(document.querySelectorAll<HTMLButtonElement>('.json-node-toggle')).find(el=>el.textContent?.includes('nested:'))!;
assert.ok(nested);nested.click();await delay(20);
assert.match(document.querySelector('[aria-label="JSON structure"]')!.textContent!,/42/);
store.closeTab(store.getState().activeTabId!);
await store.openFile('folder','invalid.json'); await delay(60);
Array.from(document.querySelectorAll<HTMLButtonElement>('.file-view-switch button')).find(el=>el.textContent==='View tree')!.click(); await delay(30);
assert.match(document.querySelector('.file-view .pane-error')!.textContent!,/Cannot preview/);
store.closeTab(store.getState().activeTabId!);
await store.openFile('folder','table.csv'); await delay(60);
assert.match(document.querySelector('.workbook-grid')!.textContent!,/Alpha/);
store.closeTab(store.getState().activeTabId!);
// Spreadsheet reader is dependable by default; blank native Quick Look is not offered for XLSX.
await store.openFile('folder','preview-workbook.xlsx'); await delay(80);
assert.match(document.querySelector('.workbook-grid')!.textContent!,/Alpha/);
assert.equal(document.querySelector('[data-cell="0:0"]')?.getAttribute('tabindex'),'0','first non-empty cell is keyboard reachable on load');
assert.match(document.querySelector('.workbook-formula')!.textContent!,/Name.*A1/,'A1 and its value are selected on load');
const excelPreviewButton=Array.from(document.querySelectorAll<HTMLButtonElement>('.native-preview-toolbar button')).find(button=>button.textContent==='Excel preview')!;
assert.equal(excelPreviewButton.getAttribute('aria-pressed'),'true','the full-sheet Excel renderer is the default');
assert.equal(document.querySelector('.native-preview-toolbar button')?.textContent,'Excel preview','unsupported blank Quick Look is not presented as an XLSX preview');
assert.equal(nativePreviewCalls.some(call=>call.command==='files.nativeShow'&&call.input.path==='preview-workbook.xlsx'),false,'opening a spreadsheet never covers its working in-app grid with an empty native surface');
const fullPageButton=document.querySelector('[aria-label="Expand Excel preview to full page"]') as HTMLButtonElement;
assert.ok(fullPageButton,'a full-page action is available from the actual open workbook');fullPageButton.click();await delay(40);
assert.equal(document.querySelector('.workspace')?.getAttribute('data-maximized'),'true','Excel full page uses the app shell maximize state');
assert.equal(document.querySelector('[aria-label="Restore resource pane"]')?.getAttribute('aria-pressed'),'true','the app-level control stays synchronized');
(document.querySelector('[aria-label="Return Excel preview to split view"]') as HTMLButtonElement).click();await delay(40);
assert.equal(document.querySelector('.workspace')?.getAttribute('data-maximized'),'false','the workbook control restores the conversation split view');
store.closeTab(store.getState().activeTabId!); await delay(20);
// Resource tabs are isolated by chat, project, and repository. Switching to
// another conversation cannot leave an earlier workbook visible in the pane.
await store.openFile('folder-a','preview-workbook.xlsx'); await delay(60);
assert.match(document.querySelector('.workbook-grid')!.textContent!,/Alpha/);
const originalFolder=chats[0].folderId;
chats[0].folderId='folder-a-alt';
emit({type:'snapshot',snapshot:{chats,folders:[],projects:[],version:2,activeChatId:'a'}}); await delay(40);
assert.equal(store.getState().tabs.length,0,'rebinding a chat to another repository gets a separate resource set');
assert.equal(document.querySelector('.workbook-grid'),null,'a repository switch hides the old workbook even within one chat');
chats[0].folderId=originalFolder;
emit({type:'snapshot',snapshot:{chats,folders:[],projects:[],version:3,activeChatId:'a'}}); await delay(40);
assert.ok(store.getState().tabs.some((tab:any)=>tab.path==='preview-workbook.xlsx'),'returning to the original repository restores its file tabs');
await store.selectChat('b'); await delay(60);
assert.equal(store.getState().tabs.length,0,'a second chat starts with no tabs from the first');
assert.equal(document.querySelector('.workbook-grid'),null,'the first chat workbook is not mounted in the second chat');
await store.openFile('folder-b','notes.md'); await delay(60);
assert.equal(store.getState().tabs.length,1);
await store.selectChat('a'); await delay(60);
assert.ok(store.getState().tabs.some((tab:any)=>tab.path==='preview-workbook.xlsx'));
assert.ok(!store.getState().tabs.some((tab:any)=>tab.path==='notes.md'));
assert.match(document.querySelector('.workbook-grid')!.textContent!,/Alpha/,'returning to a chat restores its own workbook');
store.closeTab(store.getState().tabs.find((tab:any)=>tab.path==='preview-workbook.xlsx')!.id); await delay(30);
await store.selectChat('b'); await delay(60);
assert.ok(store.getState().tabs.some((tab:any)=>tab.path==='notes.md'));
assert.ok(!store.getState().tabs.some((tab:any)=>tab.path==='preview-workbook.xlsx'));
assert.equal(document.querySelector('.workbook-grid'),null,'the workbook stays hidden after switching back');
await store.selectChat('a'); await delay(60);
await store.openFile('folder','example.ts'); await delay(40);
await store.openFile('folder-a','src/main.ts'); await delay(40);
await store.openDiff('folder-a','src/main.ts'); await delay(40);
assert.ok(store.getState().tabs.some((tab:any)=>tab.id==='file:folder-a:src/main.ts'));
assert.ok(store.getState().tabs.some((tab:any)=>tab.id==='diff:folder-a:src/main.ts'));
emit({type:'fileMoved',folderId:'folder-a',from:'src/main.ts',to:'src/renamed.ts'});
await delay(80);
assert.ok(store.getState().tabs.some((tab:any)=>tab.id==='file:folder-a:src/renamed.ts'&&tab.path==='src/renamed.ts'),'renaming a file updates its open preview reference');
assert.ok(store.getState().tabs.some((tab:any)=>tab.id==='diff:folder-a:src/renamed.ts'&&tab.title==='Diff: renamed.ts'),'renaming a file updates its open diff reference');
assert.equal(store.getState().activeTabId,'diff:folder-a:src/renamed.ts','the selected diff stays selected after its source path changes');
assert.equal(store.getState().fileBodies['file:folder-a:src/main.ts'],undefined,'old-path file bytes are discarded');
assert.equal(store.getState().diffs['diff:folder-a:src/main.ts'],undefined,'old-path diff content is discarded');
assert.equal(store.getState().diffs['diff:folder-a:src/renamed.ts']?.phase,'ready','the destination diff reloads from the new path');
const pendingDiff=store.openDiff('folder-a','src/pending.ts');
await delay(10);
assert.ok(releasePendingDiff,'the slow old-path diff request started');
emit({type:'fileMoved',folderId:'folder-a',from:'src/pending.ts',to:'src/pending-renamed.ts'});
await delay(30);
releasePendingDiff({path:'src/pending.ts',before:'stale',after:'stale',truncated:false});
await pendingDiff; await delay(20);
assert.equal(store.getState().diffs['diff:folder-a:src/pending.ts'],undefined,'a late pre-rename diff response cannot recreate old-path content');
assert.equal(store.getState().diffs['diff:folder-a:src/pending-renamed.ts']?.phase,'ready','the renamed diff remains current after the old request settles');
for(const id of ['file:folder-a:src/renamed.ts','diff:folder-a:src/renamed.ts','diff:folder-a:src/pending-renamed.ts'])store.closeTab(id);
store.activateTab('file:folder:example.ts');
await delay(30);
assert.equal(store.getState().tabs.length,1,'rename coverage leaves the surrounding lifecycle fixture unchanged');
store.setResourcesHidden(true);
await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelector('.workspace')!.hasAttribute('hidden'),true);
assert.ok(document.querySelector('.summary-card'),'hiding the optional resource surface never removes the chat summary');
const preservedTimeline=document.querySelector('.timeline');
store.setNavHidden(true);await new Promise(r=>setTimeout(r,30));
assert.ok(document.querySelector('.nav[hidden]'));
assert.ok(document.querySelector('[aria-label="Show left sidebar"]'));
assert.equal(document.querySelector('.timeline'),preservedTimeline,'navigation toggle preserves mounted conversation');
assert.equal(persisted.get('muster.navHidden'),'true');
store.setNavHidden(false);await new Promise(r=>setTimeout(r,30));
assert.ok(!document.querySelector('.nav[hidden]'));
assert.equal(document.querySelector('.timeline'),preservedTimeline);
assert.equal(store.getState().tabs.length,1,'hiding preserves resource tabs');
assert.ok(document.querySelector('[aria-label="Show resource pane"]'));
assert.equal(document.querySelector('.summary-card')?.getAttribute('aria-label'),'Chat summary','the chat summary card floats inside the conversation, not as a pane');
assert.ok(document.querySelector('.center > .summary-card'),'the summary is owned by the conversation surface');
store.activateTab(store.getState().tabs[0].id);
await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelector('.workspace')?.getAttribute('aria-label'),'Resources','resources retain a distinct adjoining pane');
assert.ok(document.querySelector('.workspace-tabs'),'an activated resource is visible alongside the summary card');
assert.ok(document.querySelector('.summary-card'),'opening resources never replaces the summary card');
store.setSummaryHidden(true);await delay(30);
assert.ok(document.querySelector('.summary-card[hidden]'),'the header toggle can hide the summary card');
assert.equal(persisted.get('muster.summaryHidden'),'true','summary visibility is remembered');
store.setSummaryHidden(false);await delay(30);
assert.equal(store.getState().summaryHidden,false);
emit({type:'timeline',chatId:'a',items:[{id:'a1',chatId:'a',kind:'assistant',text:'Chat a live update',createdAt:''},{id:'a2',chatId:'a',kind:'tool',status:'completed',text:'Read src/main.ts',data:{type:'fileRead',path:'src/main.ts'}},{id:'a3',chatId:'a',kind:'tool',status:'completed',text:'Edited src/main.ts',data:{type:'fileChange',changes:[{path:'src/main.ts',diff:'@@ -1 +1,2 @@\n-export const total = 1;\n+export const total = 2;\n+export const ready = true;'}]}},{id:'a4',chatId:'a',kind:'tool',status:'completed',text:'pnpm run typecheck\nTypecheck passed',data:{type:'commandExecution',command:'pnpm run typecheck',exitCode:0,durationMs:1800,output:'Typecheck passed'}}]});
await delay(40);
await delay(20);
const inlineChangesButton=document.querySelector('.changes-pill') as HTMLButtonElement;
assert.ok(inlineChangesButton,'completed file edits have a review control in the main conversation');inlineChangesButton.click();await delay(80);
assert.equal(document.querySelectorAll('.turn-change-preview .inline-diff-row.is-add').length,2,'the main conversation renders added code inline with syntax-aware patch rows');
assert.equal(document.querySelectorAll('.turn-change-preview .inline-diff-row.is-del').length,1,'the main conversation renders removals inline rather than opening a second pane');
assert.ok(document.querySelector('.summary-card'),'opening an inline diff leaves the summary card in place');
const settingsButton=Array.from(document.querySelectorAll<HTMLButtonElement>('.nav-footer-action')).find(button=>button.textContent?.trim()==='Settings')!;
assert.ok(settingsButton,'app-level display preferences have a reachable Settings destination');settingsButton.click();await delay(50);
store.setSettingsSection('chat');await delay(40);
const inlinePreference=document.querySelector('[aria-label="Show file diffs inline"]');
assert.equal(inlinePreference?.getAttribute('aria-checked'),'true','inline file diffs are enabled by default');store.setInlineFileDiffsVisible(false);await delay(40);
assert.equal(document.querySelector('[aria-label="Show file diffs inline"]')?.getAttribute('aria-checked'),'false','the Settings switch reflects the persisted app choice');
assert.equal(store.getState().showInlineFileDiffs,false,'the app preference immediately hides inline code previews');
assert.equal(JSON.parse(persisted.get('muster.settings.v1')??'{}')['chat.inlineDiffs'],false,'the app preference is cached for first paint');
(document.querySelector('.settings-back') as HTMLButtonElement).click();await delay(60);
assert.ok(document.querySelector('.summary-card'),'the summary card stays when inline diffs are disabled');
assert.ok(document.querySelector('.changes-pill'),'the files-changed pill stays when inline diffs are off');
(document.querySelector('.changes-pill') as HTMLButtonElement).click();await delay(40);
assert.ok(!document.querySelector('.turn-change-preview'),'with inline diffs off the pill never expands code into the transcript');
store.setInlineFileDiffsVisible(true);await delay(30);
assert.ok(document.querySelector('.changes-pill'),'re-enabling inline diffs restores the main-pane review control');
// linkedom has no layout (a 0px column), so the card is in its compact overlay form, which starts as a
// pill until expanded; expand it to reach the rows.
const summaryPill=document.querySelector<HTMLButtonElement>('.summary-card .summary-pill');
assert.ok(summaryPill,'the compact summary card starts as a pill when no fold preference is stored');
assert.equal(summaryPill!.getAttribute('aria-expanded'),'false');
assert.equal(document.querySelector('.summary-card [aria-label="Sources"]'),null,'the pill covers no transcript rows');
summaryPill!.click();await delay(30);
assert.equal(document.querySelector('.summary-card .summary-pill'),null,'the pill expands into the card');
assert.equal(document.querySelector('.summary-card .summary-collapse')?.getAttribute('aria-expanded'),'true','the expanded compact card offers its collapse chevron');
const activitySource=Array.from(document.querySelectorAll<HTMLButtonElement>('.summary-card [aria-label="Sources"] .summary-row')).find(button=>button.title?.includes('src/main.ts'))!;
assert.ok(activitySource,'the summary card lists files reported by the active chat timeline: '+document.querySelector('.summary-card')?.innerHTML);
activitySource.click();await delay(80);
assert.ok(document.querySelector('.summary-card'),'opening a source keeps the summary card mounted');
assert.equal(store.getState().activeTabId,'file:folder-a:src/main.ts','a source row opens that exact file in its attached chat folder');
assert.equal(document.querySelectorAll('.file-inline-diff-added').length,2,'the open source file decorates the provider additions in place');
assert.equal(document.querySelectorAll('.file-inline-diff-deleted').length,1,'removed source appears as an inline deleted-line widget');
assert.match(document.querySelector('.inline-file-diff-legend')!.textContent!,/Agent edit/,'the live source identifies the provenance of its inline diff');
store.closeTab('file:folder-a:src/main.ts');await delay(30);
await store.openFile('folder','example.ts');
await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelectorAll('.workspace').length,1,'opening a reference reveals hidden resources');
assert.equal(store.getState().activeChatId,'a');
window.innerWidth=760;window.dispatchEvent(new window.Event('resize'));
await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelectorAll('.workspace').length,0,'narrow window must preserve readable chat width');
const compact=document.querySelector('.resource-compact-open') as HTMLButtonElement;
assert.ok(compact,'resources can be reopened at narrow widths');
compact.click();await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelector('.workspace')?.getAttribute('data-maximized'),'true');
(document.querySelector('.resource-maximize') as HTMLButtonElement).click();
await new Promise(r=>setTimeout(r,80));
assert.ok(document.querySelector('.resource-compact-open'));
window.innerWidth=1280;window.dispatchEvent(new window.Event('resize'));
store.closeTab(store.getState().tabs[0].id);
await new Promise(r=>setTimeout(r,80));
assert.equal(store.getState().resourcesHidden,true,'closing the final resource returns its width to the conversation');
assert.equal(persisted.get('muster.resourcesHidden'),'true');
(document.querySelector('[aria-label="Show resource pane"]') as HTMLButtonElement).click();
await new Promise(r=>setTimeout(r,80));
assert.deepEqual(Array.from(document.querySelectorAll('.resource-launchers button')).map(button=>button.textContent),['Browser','Terminal'],'a chat without a folder offers only tiles that work');
assert.match(document.querySelector('.resource-launchers-note')?.textContent??'',/need|appear/i,'one line explains why Files and Changes are absent');
// NAV-13: nothing is inert and nothing invents a repository: the note names where Terminal runs, and attaching a folder is explicit.
assert.equal(document.querySelector('.resource-launchers-attach')?.textContent,'Attach Folder…','a chat without a usable folder offers an explicit Attach Folder action');
{const saved=chats[0].folderId;delete (chats[0] as any).folderId;emit({type:'snapshot',snapshot:{chats,folders:[],projects:[],version:40,activeChatId:'a'}});await new Promise(r=>setTimeout(r,60));
assert.match(document.querySelector('.resource-launchers-note')?.textContent??'',/private scratch folder/,'a folderless chat says Terminal runs in its private scratch folder, not the user’s files');
chats[0].folderId=saved;emit({type:'snapshot',snapshot:{chats,folders:[],projects:[],version:41,activeChatId:'a'}});await new Promise(r=>setTimeout(r,60));}
const group=Array.from(document.querySelectorAll<HTMLButtonElement>('.nav-disclosure')).find(el=>el.textContent==='Chats')!;
group.click();await new Promise(r=>setTimeout(r,80));
assert.equal(group.getAttribute('aria-expanded'),'false');
assert.deepEqual(JSON.parse(persisted.get('muster.sidebar.v1')!).collapsed,['chats']);
// Spreadsheet navigation and shrinking live refresh must never leave a blank page.
const {WorkbookFile}=await import('../src/renderer/components/WorkbookFile');
let selection='';
let fullPageToggles=0;
const tableRoot=document.createElement('div');document.body.append(tableRoot);
const tableReact=createRoot(tableRoot);
const workbook={revision:'one',sheets:[{name:'Data',rows:Array.from({length:250},(_,i)=>[String(i),'row '+i]),formulas:{},limited:false}],limited:false};
tableReact.render(<WorkbookFile workbook={workbook} onLocation={value=>{selection=value;}} onToggleFullPage={()=>fullPageToggles++}/>);await delay(40);
const expandExcel=tableRoot.querySelector('[aria-label="Expand Excel preview to full page"]') as HTMLButtonElement;
assert.ok(expandExcel,'Excel exposes a full-page control in its toolbar');expandExcel.click();assert.equal(fullPageToggles,1,'full-page control delegates pane layout to the app shell');
assert.ok(tableRoot.querySelectorAll('.workbook-grid thead th').length>=9,'sheet headers continue across the visible viewport beyond used columns');
(tableRoot.querySelector('[aria-label="Next rows"]') as HTMLButtonElement).click();await delay(20);
assert.match(tableRoot.querySelector('.workbook-pages')!.textContent!,/101–200 of 250/);
(tableRoot.querySelector('[data-cell="100:1"]') as HTMLButtonElement).click();await delay(20);
assert.equal(selection,'Data!B101');
const down=new window.Event('keydown',{bubbles:true});Object.assign(down,{key:'ArrowDown'});
tableRoot.querySelector('[data-cell="100:1"]')!.dispatchEvent(down);await delay(20);
assert.match(tableRoot.querySelector('[data-selected="true"]')!.textContent!,/row 101/);
tableReact.render(<WorkbookFile workbook={{...workbook,revision:'two',sheets:[{...workbook.sheets[0],rows:[['short','refresh']]}]}} onLocation={value=>{selection=value;}}/>);await delay(40);
assert.match(tableRoot.querySelector('.workbook-pages')!.textContent!,/1–1 of 1 rows/);
assert.match(tableRoot.querySelector('.workbook-grid')!.textContent!,/refresh/);
assert.ok(tableRoot.querySelectorAll('.workbook-grid tbody tr').length>1,'sheet surface fills the viewport with addressable blank Excel rows after used data');
assert.equal(tableRoot.querySelector('[data-selected="true"]')?.getAttribute('data-selected'),'true','refreshed sheet selects its first available cell');
(tableRoot.querySelector('[data-cell="15:7"]') as HTMLButtonElement).click();await delay(20);
assert.equal(tableRoot.querySelector('.workbook-grid td[data-selected="true"] button')?.getAttribute('aria-label'),'H16 (blank)','visible empty worksheet cells remain selectable and announce their address');
assert.match(tableRoot.querySelector('.workbook-grid thead')!.textContent!,/H/,'worksheet column letters continue across the visible blank grid');
(tableRoot.querySelector('[aria-label="Wrap cell text"]') as HTMLButtonElement).click();await delay(20);
assert.equal(tableRoot.querySelector('.workbook-grid')!.getAttribute('data-wrap'),'true');
tableReact.render(<WorkbookFile workbook={workbook} onLocation={value=>{selection=value;}} fullPage onToggleFullPage={()=>fullPageToggles++}/>);await delay(20);
const restoreExcel=tableRoot.querySelector('[aria-label="Return Excel preview to split view"]') as HTMLButtonElement;
assert.equal(restoreExcel.getAttribute('aria-pressed'),'true','the worksheet reflects full-page state');restoreExcel.click();assert.equal(fullPageToggles,2,'the same control returns to split view');
tableReact.unmount();tableRoot.remove();
console.log('PASS: spreadsheet keyboard navigation, bounded pages, refresh clamping and text wrapping');
root.unmount();
const restoredRoot=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
restoredRoot.render(<React.StrictMode><App/></React.StrictMode>);await new Promise(r=>setTimeout(r,80));
const restoredGroup=Array.from(document.querySelectorAll<HTMLButtonElement>('.nav-disclosure')).find(el=>el.textContent==='Chats')!;
assert.equal(restoredGroup.getAttribute('aria-expanded'),'false','collapse survives full component remount');
assert.deepEqual(errors,[]);restoredRoot.unmount();

// Deferred acknowledgement must preserve edits made in either mounted chat.
let rejectSend: (error: Error) => void = () => {};
let acceptSend: (result: { runId: string }) => void = () => {};
const requests: { id: string; text: string; requestId: string }[] = [];
const durableDrafts: Record<string, string> = {};
const previousInvoke = window.muster.invoke;
window.muster.invoke = async (command: string, params: { id: string; draft: string; text: string; requestId: string }) => {
  if (command === 'chat.update') { durableDrafts[params.id] = params.draft; return; }
  if (command === 'chat.send') {
    requests.push(params);
    const deferred = Promise.withResolvers<{ runId: string }>();
    acceptSend = deferred.resolve;
    rejectSend = deferred.reject;
    return deferred.promise;
  }
  return previousInvoke(command, params);
};
store.setComposerDraft('a', '  first draft\n');
const firstSend = store.sendMessage('a', '  first draft\n');
await delay(0);
assert.equal(await store.sendMessage('a', '  first draft\n'), false, 'double activation cannot dispatch a second request');
store.setComposerDraft('a', 'newer text');
store.setComposerDraft('b', 'other chat draft');
rejectSend(new Error('Transport disconnected'));
assert.equal(await firstSend, false);
assert.equal(store.getState().composerDrafts.a.text, 'newer text', 'late failure never replaces newer input');
assert.equal(store.getState().composerDrafts.b.text, 'other chat draft', 'failure never writes another chat');
await store.flushComposerDraft('a');
await store.flushComposerDraft('b');
assert.equal(durableDrafts.a, 'newer text');
assert.equal(durableDrafts.b, 'other chat draft');

store.setComposerDraft('a', '  first draft\n');
const retrySend = store.sendMessage('a', '  first draft\n');
await delay(0);
assert.equal(requests[1].requestId, requests[0].requestId, 'ambiguous retry reuses durable send identity');
assert.equal(requests[1].text, '  first draft\n', 'submission preserves whitespace');
store.setComposerDraft('a', 'text entered during retry');
acceptSend({ runId: 'accepted-original' });
assert.equal(await retrySend, true);
assert.equal(durableDrafts.a, 'text entered during retry', 'late success preserves the newer durable draft');

const finalSend = store.sendMessage('a', 'text entered during retry');
await delay(0);
acceptSend({ runId: 'accepted-next' });
assert.equal(await finalSend, true);
assert.equal(durableDrafts.a, '', 'only acknowledged unchanged draft is cleared');
assert.equal(requests.length, 3, 'double activation produced no extra turn');
console.log('PASS: send failure, ambiguous retry, duplicate activation and late success retain the correct per-chat draft');
console.log("PASS: repeated chat switching keeps one transcript and composer, with no stale messages or render errors");

// Notices: errors persist and coalesce with a count, actions run once, and archive/unpin offer Undo.
const shellRoot=createRoot(document.getElementById('root')!,{onUncaughtError:error=>(errors as unknown[]).push(error)});shellRoot.render(<App/>);await delay(40);
for (const notice of store.getState().notices) store.dismissNotice(notice.id);
store.notifyError(new Error('Disk full'));
store.notifyError(new Error('Disk full'));
const diskErrors = store.getState().notices.filter(notice => notice.kind === 'error');
assert.equal(diskErrors.length, 1, 'identical errors coalesce into one notice');
assert.equal(diskErrors[0]!.count, 2);
assert.equal(store.noticeLifetime({kind:'error'}), null, 'errors stay until dismissed');
assert.equal(store.noticeLifetime({kind:'success'}), 4000, 'plain success confirms briefly');
assert.equal(store.runtimeNoticeKind('Could not add folder: denied'), 'error');
assert.equal(store.runtimeNoticeKind('Added folder src'), 'info');
await delay(30);
assert.equal(document.querySelector('.notice[data-kind="error"] .notice-count')?.textContent, '×2');
let retried = 0;
store.notifyError(new Error('Push failed'), () => { retried++; });
await delay(30);
const retryButton = Array.from(document.querySelectorAll<HTMLButtonElement>('.notice-action')).find(button => button.textContent === 'Retry');
assert.ok(retryButton, 'a failure with a retry renders a Retry action');
retryButton!.click();
await delay(30);
assert.equal(retried, 1);
assert.ok(!store.getState().notices.some(notice => notice.message === 'Push failed'), 'running an action dismisses its notice');
for (let index = 0; index < 6; index++) store.notifySuccess(`Saved ${index}`);
assert.ok(store.getState().notices.length <= 4, 'the stack stays bounded');
assert.ok(store.getState().notices.some(notice => notice.message === 'Disk full'), 'transient rows leave before a persistent error');
for (const notice of store.getState().notices) store.dismissNotice(notice.id);
assert.equal(await store.updateChat('b', {archived: true}), true);
const archived = store.getState().notices.find(notice => notice.message === 'Archived “b”');
assert.equal(archived?.action?.label, 'Undo');
store.runNoticeAction(archived!.id);
await delay(30);
assert.equal(store.getState().snapshot!.chats.find(chat => chat.id === 'b')!.archived, false, 'Undo restores the archived chat');
assert.equal(store.getState().notices.length, 0, 'the undo itself does not offer another undo');
await store.updateChat('b', {pinned: true});
await store.updateChat('b', {pinned: false});
const unpinned = store.getState().notices.find(notice => notice.message === 'Unpinned “b”');
store.runNoticeAction(unpinned!.id);
await delay(30);
assert.equal(store.getState().snapshot!.chats.find(chat => chat.id === 'b')!.pinned, true, 'Undo re-pins');
await store.updateChat('b', {pinned: false}, {undoable: false});
for (const notice of store.getState().notices) store.dismissNotice(notice.id);
console.log('PASS: errors persist and coalesce, Retry and Undo actions run once, and the notice stack stays bounded');

// Settings shell: nav sections, preferences applied to <html>.
assert.equal(document.documentElement.getAttribute('data-send-key'), 'enter');
store.openAppSettings('storage');
await delay(30);
assert.equal(document.querySelectorAll('.settings-nav-item').length, 12);
assert.equal(document.querySelector('.settings-nav-item[aria-current="page"]')?.textContent, 'Storage');
store.setSettingsSection('chat');
await delay(30);
assert.ok(document.querySelector('.preference-switch[aria-label="Show file diffs inline"]'));
assert.equal(await store.setSetting('general.spellcheck', false), true);
await delay(30);
assert.equal(document.documentElement.getAttribute('spellcheck'), 'false');
await store.setSetting('general.spellcheck', true);
store.closeSettings();
await delay(30);
assert.deepEqual(errors, []);
shellRoot.unmount();
console.log('PASS: settings shell renders its sections and applies preferences to the document');
