import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const {parseHTML} = require('linkedom');
const {window} = parseHTML('<html><body><div id="root"></div></body></html>');
window.innerWidth=1280;
window.innerHeight=840;
const persisted = new Map<string,string>();
Object.assign(globalThis,{window, document:window.document, HTMLElement:window.HTMLElement, Element:window.Element, localStorage:{getItem(key:string){return persisted.get(key)??null},setItem(key:string,value:string){persisted.set(key,value)}},requestAnimationFrame:(cb:any)=>setTimeout(cb,0),cancelAnimationFrame:clearTimeout, ResizeObserver:class {observe(){}unobserve(){}disconnect(){}}});
Object.defineProperty(window.HTMLElement.prototype,'scrollHeight',{get(){return 800}});
Object.defineProperty(window.HTMLElement.prototype,'clientHeight',{get(){return 500}});
Object.defineProperty(window.HTMLElement.prototype,'offsetHeight',{get(){return 70}});
Object.defineProperty(window.HTMLElement.prototype,'offsetWidth',{get(){return 800}});
window.HTMLElement.prototype.getBoundingClientRect=()=>({height:500,width:800,top:0,left:0,bottom:500,right:800});
window.HTMLElement.prototype.scrollTo=function({top}:any){this.scrollTop=top};
const chats=['a','b'].map(id=>({id,title:id,pinned:false,archived:false,draft:'',status:'completed',updatedAt:'',model:'test',mode:'agent'}));
let eventListener: (event:any)=>void = ()=>{};
let fileVersion = 1;
window.muster={subscribe(listener:any){eventListener=listener;return()=>{}},async invoke(c:string,p:any){if(c==='files.read')return {path:p.path,text:'Version '+fileVersion,truncated:false};if(c==='workspace.watch')return; if(c==='app.snapshot')return {chats,folders:[],projects:[],version:1,activeChatId:'a'};if(c==='chat.select')return [{id:p.id+'1',chatId:p.id,kind:'assistant',text:'Chat '+p.id,createdAt:''}];}};
const React=await import('react');
const {createRoot}=await import('react-dom/client');
const {App}=await import('../src/renderer/App');
const store=await import('../src/renderer/store');
const errors: unknown[] = [];
const root=createRoot(document.getElementById('root')!, {onUncaughtError:error=>errors.push(error)});root.render(<React.StrictMode><App/></React.StrictMode>);await store.boot();
for(const id of ['a','b','a','b','a']){await store.selectChat(id);await new Promise(r=>setTimeout(r,80));assert.equal(document.querySelectorAll('.timeline').length,1, 'exactly one mounted transcript after selecting '+id);assert.equal(document.querySelectorAll('.composer').length,1);assert.match(document.querySelector('.timeline')!.textContent!,new RegExp('Chat '+id));assert.doesNotMatch(document.querySelector('.timeline')!.textContent!,new RegExp('Chat '+(id==='a'?'b':'a')));assert.deepEqual(errors,[]);}
await store.openFile('folder','example.ts');
await new Promise(r=>setTimeout(r,80));
assert.match(document.querySelector('.file-view')!.textContent!,/Version 1/);
fileVersion=2;eventListener({type:'workspaceChanged',folderId:'folder'});
await new Promise(r=>setTimeout(r,80));
assert.match(document.querySelector('.file-view')!.textContent!,/Version 2/);
assert.equal(store.getState().activeChatId,'a','resource refresh must not switch chats');
assert.equal(document.querySelectorAll('.timeline').length,1);
store.setResourcesHidden(true);
await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelector('.workspace')!.hasAttribute('hidden'),true);
const preservedTimeline=document.querySelector('.timeline');
store.setNavHidden(true);await new Promise(r=>setTimeout(r,30));
assert.ok(document.querySelector('.nav[hidden]'));
assert.ok(document.querySelector('[aria-label="Show left sidebar"]'));
assert.equal(document.querySelector('.timeline'),preservedTimeline,'navigation toggle preserves mounted conversation');
assert.equal(persisted.get('muster.navHidden'),'true');
store.setNavHidden(false);await new Promise(r=>setTimeout(r,30));
assert.ok(!document.querySelector('.nav[hidden]'));
assert.equal(document.querySelector('.timeline'),preservedTimeline);
assert.equal(store.getState().tabs.length,1,'hiding preserves resource tabs');
assert.ok(document.querySelector('[aria-label="Show resource pane"]'));
await store.openFile('folder','example.ts');
await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelectorAll('.workspace').length,1,'opening a reference reveals hidden resources');
assert.equal(store.getState().activeChatId,'a');
window.innerWidth=760;window.dispatchEvent(new window.Event('resize'));
await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelectorAll('.workspace').length,0,'narrow window must preserve readable chat width');
const compact=document.querySelector('.resource-compact-open') as HTMLButtonElement;
assert.ok(compact,'resources can be reopened at narrow widths');
compact.click();await new Promise(r=>setTimeout(r,80));
assert.equal(document.querySelector('.workspace')?.getAttribute('data-maximized'),'true');
(document.querySelector('.resource-maximize') as HTMLButtonElement).click();
await new Promise(r=>setTimeout(r,80));
assert.ok(document.querySelector('.resource-compact-open'));
window.innerWidth=1280;window.dispatchEvent(new window.Event('resize'));
store.closeTab(store.getState().tabs[0].id);
await new Promise(r=>setTimeout(r,80));
assert.ok(document.querySelector('.workspace-empty'),'closing final resource leaves a useful empty pane');
store.setResourcesHidden(true);
await new Promise(r=>setTimeout(r,80));
(document.querySelector('[aria-label="Show resource pane"]') as HTMLButtonElement).click();
await new Promise(r=>setTimeout(r,80));
assert.ok(document.querySelector('.workspace-empty'),'empty pane can be hidden and reopened');
const group=Array.from(document.querySelectorAll<HTMLButtonElement>('.nav-disclosure')).find(el=>el.textContent==='Chats')!;
group.click();await new Promise(r=>setTimeout(r,80));
assert.equal(group.getAttribute('aria-expanded'),'false');
assert.deepEqual(JSON.parse(persisted.get('muster.sidebar.v1')!).collapsed,['chats']);
root.unmount();
const restoredRoot=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
restoredRoot.render(<React.StrictMode><App/></React.StrictMode>);await new Promise(r=>setTimeout(r,80));
const restoredGroup=Array.from(document.querySelectorAll<HTMLButtonElement>('.nav-disclosure')).find(el=>el.textContent==='Chats')!;
assert.equal(restoredGroup.getAttribute('aria-expanded'),'false','collapse survives full component remount');
assert.deepEqual(errors,[]);restoredRoot.unmount();
console.log("PASS: repeated chat switching keeps one transcript and composer, with no stale messages or render errors");
