/** Run with node tests/run-sidebar-navigation.mjs; dynamic chunks initialize UI after the DOM. */
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {setTimeout as delay} from 'node:timers/promises';
const require=createRequire(import.meta.url),{parseHTML}=require('linkedom');
const {window}=parseHTML('<html><body><div id="root"></div></body></html>');
const saved=new Map<string,string>(),scrolls:string[]=[];
Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,MutationObserver:window.MutationObserver,ResizeObserver:class{observe(){}disconnect(){}},requestAnimationFrame:(fn:any)=>setTimeout(fn,0),cancelAnimationFrame:clearTimeout,localStorage:{getItem:(key:string)=>saved.get(key)??null,setItem:(key:string,value:string)=>saved.set(key,value)}});
const styles=()=>({getPropertyValue:()=>'',direction:'ltr',position:'static',overflow:'visible',overflowX:'visible',overflowY:'visible',display:'block',animationName:'none',transitionProperty:'none',transitionDuration:'0s',animationDuration:'0s',paddingTop:'0px',paddingBottom:'0px',paddingLeft:'0px',paddingRight:'0px'});
Object.assign(globalThis,{getComputedStyle:styles});window.getComputedStyle=styles;
window.HTMLElement.prototype.getBoundingClientRect=()=>({x:0,y:0,width:224,height:30,left:0,top:0,right:224,bottom:30});
window.HTMLElement.prototype.getClientRects=function(){return [this.getBoundingClientRect()];};
window.HTMLElement.prototype.scrollIntoView=function(){scrolls.push(this.dataset.chatId);};
let chats=['one','two'].map((id,index)=>({id,title:id,folderId:'folder',status:index?'running':'completed',updatedAt:'now',pinned:false,archived:false,draft:'',model:'fixture',mode:'agent'}));
let listener:(event:any)=>void=()=>{};
const calls:{command:string;input:any}[]=[];
let contextMenuAction:any=null;
const snapshot=()=>({version:1,chats,folders:[{id:'folder',name:'Folder',path:'/fixture'}],projects:[],activeChatId:'one'});
window.muster={subscribe(fn:any){listener=fn;return()=>{};},async invoke(command:string,input:any){
  calls.push({command,input});
  if(command==='chat.contextMenu')return contextMenuAction;
  if(command==='app.snapshot')return snapshot();
  if(command==='chat.timeline')return {items:[],revision:0};
  if(command==='chat.update'){chats=chats.map(chat=>chat.id===input.id?{...chat,...input}:chat);listener({type:'snapshot',snapshot:snapshot()});return chats.find(chat=>chat.id===input.id);}
  if(command==='chat.contextTelemetry')return {usedTokens:null,windowTokens:null,source:null,compacted:false,updatedAt:null};
}};
const React=await import('react'),{createRoot}=await import('react-dom/client');
const store=await import('../src/renderer/store'),{Sidebar}=await import('../src/renderer/components/Sidebar');
const errors:unknown[]=[];const root=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
await store.boot();root.render(<Sidebar/>);await delay(60);
assert.deepEqual(errors,[]);assert.ok(document.querySelector('[aria-label="1 active chats"]'),'running group count remains visible when collapsed');
const footerLabels=Array.from(document.querySelectorAll<HTMLElement>('.nav-footer-action')).map(button=>button.textContent);
assert.deepEqual(footerLabels,['Skills & plugins','Accounts & providers'],'sidebar utilities remain legible at the minimum navigation width');
const group=document.querySelector('.nav-disclosure') as HTMLButtonElement;group.click();await delay(30);assert.equal(group.getAttribute('aria-expanded'),'false');
await store.selectChat('two');await delay(45);
assert.equal(group.getAttribute('aria-expanded'),'true');assert.equal(scrolls.at(-1),'two');
const count=scrolls.length;listener({type:'snapshot',snapshot:{...snapshot(),chats:chats.map(chat=>({...chat,updatedAt:'stream-update'}))}});await delay(35);assert.equal(scrolls.length,count,'stream updates do not force sidebar scrolling');
const selected=document.querySelector('[data-chat-id="two"] .chat-row-main')!;
const timelineReadsBeforeDoubleClick=calls.filter(call=>call.command==='chat.timeline').length;
selected.dispatchEvent(new window.Event('click',{bubbles:true}));selected.dispatchEvent(new window.Event('click',{bubbles:true}));selected.dispatchEvent(new window.Event('dblclick',{bubbles:true}));await delay(20);
assert.equal(calls.filter(call=>call.command==='chat.timeline').length,timelineReadsBeforeDoubleClick,'native double click on the active chat does not trigger redundant timeline reloads');
assert.equal(document.querySelector('[aria-label="Chat title"]'),null,'double click follows native row activation instead of custom rename');
contextMenuAction='pin';
const contextClick=new window.Event('contextmenu',{bubbles:true,cancelable:true});Object.assign(contextClick,{clientX:42,clientY:64});selected.dispatchEvent(contextClick);await delay(35);
assert.ok(contextClick.defaultPrevented,'right click suppresses Chromium custom menu in favor of native macOS menu');
assert.ok(calls.some(call=>call.command==='chat.contextMenu'&&call.input.id==='two'&&call.input.x===42&&call.input.y===64),'right click asks the native main-process menu at the pointer location');
assert.ok(chats.find(chat=>chat.id==='two')?.pinned,'native menu action is applied through the chat service');
contextMenuAction='rename';
const keyboard=new window.Event('keydown',{bubbles:true,cancelable:true});Object.assign(keyboard,{key:'F10',shiftKey:true});document.querySelector('[data-chat-id="two"] .chat-row-main')!.dispatchEvent(keyboard);await delay(70);
assert.deepEqual(errors,[]);assert.ok(!document.querySelector('[role="menu"]'),'native menu is not redrawn as a custom renderer popover');
assert.ok(calls.some(call=>call.command==='chat.contextMenu'&&call.input.id==='two'),'Shift+F10 opens the native menu for the focused chat');
await delay(20);assert.ok(document.querySelector('[aria-label="Chat title"]'),'native Rename action enters the existing rename flow');
const rename=document.querySelector('[aria-label="Chat title"]') as HTMLInputElement;
const before=calls.filter(call=>call.command==='chat.update').length;
const escape=new window.Event('keydown',{bubbles:true,cancelable:true});Object.assign(escape,{key:'Escape'});rename.dispatchEvent(escape);await delay(35);
assert.equal(calls.filter(call=>call.command==='chat.update').length,before,'Escape never submits rename on blur');
assert.equal(document.querySelector('[aria-label="Chat title"]'),null);
contextMenuAction='copy-link';
const trigger=document.querySelector('[aria-label="Actions for two"]') as HTMLButtonElement;trigger.click();await delay(50);
assert.ok(calls.some(call=>call.command==='clipboard.write'&&call.input.text==='muster://chat/two'),'sidebar menu copies a local link for the chat under the pointer');
assert.ok(store.getState().notices.some(notice=>notice.message==='Local chat link copied'),'successful copy confirms through the accessible notice channel');
root.unmount();await delay(20);assert.deepEqual(errors,[]);
console.log('PASS: sidebar selection reveal, stable streaming scroll, native context menu routing, authoritative pin and cancelled rename');
