/** Run with node tests/run-sidebar-navigation.mjs; dynamic chunks initialize UI after the DOM. */
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {setTimeout as delay} from 'node:timers/promises';
const require=createRequire(import.meta.url),{parseHTML}=require('linkedom');
const {window}=parseHTML('<html><body><div id="root"></div></body></html>');
const saved=new Map<string,string>(),scrolls:string[]=[];
Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,Node:window.Node,MutationObserver:window.MutationObserver,ResizeObserver:class{observe(){}disconnect(){}},requestAnimationFrame:(fn:any)=>setTimeout(fn,0),cancelAnimationFrame:clearTimeout,localStorage:{getItem:(key:string)=>saved.get(key)??null,setItem:(key:string,value:string)=>saved.set(key,value)}});
const styles=()=>({getPropertyValue:()=>'',direction:'ltr',position:'static',overflow:'visible',overflowX:'visible',overflowY:'visible',display:'block',animationName:'none',transitionProperty:'none',transitionDuration:'0s',animationDuration:'0s',paddingTop:'0px',paddingBottom:'0px',paddingLeft:'0px',paddingRight:'0px'});
Object.assign(globalThis,{getComputedStyle:styles});window.getComputedStyle=styles;
window.HTMLElement.prototype.getBoundingClientRect=()=>({x:0,y:0,width:224,height:30,left:0,top:0,right:224,bottom:30});
window.HTMLElement.prototype.getClientRects=function(){return [this.getBoundingClientRect()];};
window.HTMLElement.prototype.scrollIntoView=function(){scrolls.push(this.dataset.chatId);};
let chats=['one','two'].map((id,index)=>({id,title:id,folderId:'folder',status:index?'running':'completed',updatedAt:'now',pinned:false,archived:false,draft:'',model:'fixture',mode:'agent'}));
let listener:(event:any)=>void=()=>{};
const calls:{command:string;input:any}[]=[];
const snapshot=()=>({version:1,chats,folders:[{id:'folder',name:'Folder',path:'/fixture'}],projects:[],activeChatId:'one'});
window.muster={subscribe(fn:any){listener=fn;return()=>{};},async invoke(command:string,input:any){
  calls.push({command,input});
  if(command==='app.snapshot')return snapshot();
  if(command==='chat.timeline')return {items:[],revision:0};
  if(command==='chat.update'){chats=chats.map(chat=>chat.id===input.id?{...chat,...input}:chat);listener({type:'snapshot',snapshot:snapshot()});return chats.find(chat=>chat.id===input.id);}
  if(command==='chat.contextTelemetry')return {usedTokens:null,windowTokens:null,source:null,compacted:false,updatedAt:null};
}};
const React=await import('react'),{createRoot}=await import('react-dom/client');
const store=await import('../src/renderer/store'),{Sidebar}=await import('../src/renderer/components/Sidebar');
const errors:unknown[]=[];const root=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
await store.boot();root.render(<Sidebar/>);await delay(60);
assert.deepEqual(errors,[]);assert.ok(document.querySelector('[aria-label="1 active chats"]'),'running group count remains visible when collapsed');
const footerLabels=Array.from(document.querySelectorAll<HTMLElement>('.nav-footer-action')).map(button=>button.textContent);
assert.deepEqual(footerLabels,['Skills & plugins','Accounts & providers'],'sidebar utilities remain legible at the minimum navigation width');
const group=document.querySelector('.nav-disclosure') as HTMLButtonElement;group.click();await delay(30);assert.equal(group.getAttribute('aria-expanded'),'false');
await store.selectChat('two');await delay(45);
assert.equal(group.getAttribute('aria-expanded'),'true');assert.equal(scrolls.at(-1),'two');
const count=scrolls.length;listener({type:'snapshot',snapshot:{...snapshot(),chats:chats.map(chat=>({...chat,updatedAt:'stream-update'}))}});await delay(35);assert.equal(scrolls.length,count,'stream updates do not force sidebar scrolling');
const selected=document.querySelector('[data-chat-id="two"] .chat-row-main')!;
const keyboard=new window.Event('keydown',{bubbles:true,cancelable:true});Object.assign(keyboard,{key:'F10',shiftKey:true});selected.dispatchEvent(keyboard);await delay(70);
assert.deepEqual(errors,[]);assert.ok(document.querySelector('[role="menu"]'),'Shift+F10 opens actions for the focused chat');
const items=Array.from(document.querySelectorAll<HTMLElement>('[role="menuitem"]'));
assert.ok(items.some(item=>item.textContent==='Pin chat'));assert.ok(items.some(item=>item.textContent==='Archive chat'));assert.ok(!items.some(item=>/Share|Fork|Delete/.test(item.textContent??'')));
items.find(item=>item.textContent==='Pin chat')!.click();await delay(50);
assert.ok(calls.some(call=>call.command==='chat.update'&&call.input.id==='two'&&call.input.pinned===true));
const trigger=document.querySelector('[aria-label="Actions for two"]') as HTMLButtonElement;trigger.click();await delay(50);
Array.from(document.querySelectorAll<HTMLElement>('[role="menuitem"]')).find(item=>item.textContent==='Rename chat')!.click();await delay(35);
const rename=document.querySelector('[aria-label="Chat title"]') as HTMLInputElement;assert.ok(rename);
const before=calls.filter(call=>call.command==='chat.update').length;
const escape=new window.Event('keydown',{bubbles:true,cancelable:true});Object.assign(escape,{key:'Escape'});rename.dispatchEvent(escape);await delay(35);
assert.equal(calls.filter(call=>call.command==='chat.update').length,before,'Escape never submits rename on blur');
assert.equal(document.querySelector('[aria-label="Chat title"]'),null);
root.unmount();await delay(20);assert.deepEqual(errors,[]);
console.log('PASS: sidebar selection reveal, stable streaming scroll, keyboard actions, authoritative pin and cancelled rename');
