import {createRequire} from 'node:module';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
const require=createRequire(import.meta.url);
const {parseHTML}=require('linkedom');
const {window}=parseHTML('<html><body><div id="root"></div></body></html>');
Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,localStorage:{getItem(){return null},setItem(){}},requestAnimationFrame:(cb:any)=>setTimeout(cb,0),cancelAnimationFrame:clearTimeout});
(window.HTMLElement.prototype as any).attachEvent=function(){};(window.HTMLElement.prototype as any).detachEvent=function(){};
const calls:string[]=[];
const automation=(id:string,patch:any)=>({id,name:id,prompt:'p',target:{kind:'new',mode:'agent'},schedule:{kind:'interval',minutes:60},timezone:'UTC',permissionMode:'workspace',overlap:'skip',catchUp:'one',paused:false,createdAt:'',updatedAt:'',version:1,summary:'Every hour',issues:[],...patch});
const list=[automation('Nightly tests',{target:{kind:'new',folderId:'f1',mode:'agent'},nextRunAt:new Date(Date.now()+3600_000).toISOString()}),automation('Elsewhere',{target:{kind:'new',folderId:'f2',mode:'agent'}}),automation('Paused sweep',{target:{kind:'new',folderId:'f1',mode:'agent'},paused:true})];
window.muster={subscribe(){return()=>{}},async invoke(command:string){calls.push(command);if(command==='automations.list')return list;}} as any;
const React=await import('react');
const {createRoot}=await import('react-dom/client');
const store=await import('../src/renderer/store');
const {SummaryScheduled}=await import('../src/renderer/components/SummaryScheduled');
const errors:unknown[]=[];
const root=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
root.render(<SummaryScheduled folderIds={['f1']}/>);await delay(50);
assert.deepEqual(errors,[]);
assert.ok(calls.includes('automations.list'),'loads automations when the card needs them');
const section=document.querySelector('[aria-label="Scheduled"]');
assert.ok(section,'the Scheduled section renders');
const rows=Array.from(section!.querySelectorAll('.summary-row')).map(row=>row.textContent);
assert.equal(rows.length,2);
assert.match(rows[0]!,/Nightly tests.*Next /);
assert.match(rows[1]!,/Paused sweep.*Paused/);
assert.doesNotMatch(section!.textContent!,/Elsewhere/);
(section!.querySelector('.summary-row') as HTMLButtonElement).click();await delay(20);
assert.equal(store.getState().screen,'automations','a row opens Automations');
root.render(<SummaryScheduled folderIds={['f3']}/>);await delay(20);
assert.equal(document.querySelector('[aria-label="Scheduled"]'),null,'hidden when nothing targets the folder');
root.unmount();
console.log('Summary Scheduled section passed.');
