import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {setTimeout as delay} from 'node:timers/promises';
const require=createRequire(import.meta.url);
const {window}=require('linkedom').parseHTML('<html><body><div id="root"></div></body></html>');
window.innerWidth=1000;window.innerHeight=800;
Object.assign(globalThis,{window,document:window.document,HTMLElement:window.HTMLElement,Element:window.Element,localStorage:{getItem(){return null;},setItem(){}},requestAnimationFrame:(cb:any)=>setTimeout(cb,0),cancelAnimationFrame:clearTimeout,ResizeObserver:class{observe(){}unobserve(){}disconnect(){}}});
let focused:any;Object.defineProperty(document,'activeElement',{get:()=>focused});
window.HTMLElement.prototype.focus=function(){focused=this;this.dispatchEvent(new window.Event('focusin',{bubbles:true}));};
Object.defineProperty(window.HTMLElement.prototype,'clientHeight',{get(){return 350;}});
Object.defineProperty(window.HTMLElement.prototype,'scrollHeight',{get(){return Number.parseFloat(this.querySelector('.timeline-inner')?.style.height||'350');}});
Object.defineProperty(window.HTMLElement.prototype,'offsetHeight',{get(){return this.classList.contains('timeline-row')?70:350;}});
Object.defineProperty(window.HTMLElement.prototype,'offsetWidth',{get(){return 800;}});
window.HTMLElement.prototype.getBoundingClientRect=function(){return{height:this.classList.contains('timeline-row')?70:350,width:800,top:0,left:0,bottom:350,right:800};};
window.HTMLElement.prototype.scrollTo=function({top}:any){this.scrollTop=Math.max(0,Math.min(top,this.scrollHeight-this.clientHeight));queueMicrotask(()=>this.dispatchEvent(new window.Event('scroll')));};
const React=await import('react');const {createRoot}=await import('react-dom/client');
const {Timeline}=await import('../src/renderer/components/ChatView');
const {TimelineNavigation}=await import('../src/renderer/components/TimelineNavigation');
const {summarizeTurns}=await import('../src/renderer/components/timeline-navigation-model');
const rows=Array.from({length:80},(_,index)=>({id:(index%2?'a':'u')+Math.floor(index/2),chatId:'one',kind:index%2?'assistant' as const:'user' as const,text:(index%2?'Answer ':'Request ')+Math.floor(index/2),createdAt:'2026-09-19T10:00:00Z'}));
const errors:unknown[]=[];const root=createRoot(document.getElementById('root')!,{onUncaughtError:error=>errors.push(error)});
const render=async(items=rows,key='one')=>{root.render(<Timeline key={key} chatId={key} items={items}/>);await delay(70);assert.deepEqual(errors,[]);};
await render();
let timeline=document.querySelector('.timeline') as HTMLElement;
assert.ok(document.querySelector('nav[aria-label="Conversation turns"]'));
assert.ok(document.querySelectorAll('.turn-tick').length<=33);
timeline.scrollTop=1400;timeline.dispatchEvent(new window.Event('scroll'));await delay(40);
// Explicit jump pauses tail following and saves the virtual reading anchor.
// Tail-centered rail may not currently include turn 11: use keyboard Home.
const tick=document.querySelector('.turn-tick[tabindex="0"]') as HTMLButtonElement;
const key=(node:Element,name:string)=>{const event=new window.Event('keydown',{bubbles:true,cancelable:true});Object.defineProperty(event,'key',{value:name});node.dispatchEvent(event);};
tick.dispatchEvent(new window.Event('mouseover',{bubbles:true}));await delay(10);
assert.ok(document.querySelector('[role="tooltip"][data-native-preview-overlay]'),'hover preview participates in native overlay suppression');
tick.dispatchEvent(new window.Event('mouseout',{bubbles:true}));await delay(10);
key(tick,'Home');await delay(20);
assert.equal(document.activeElement?.getAttribute('aria-label'),'Turn 1: Request 0');
assert.match(document.querySelector('[role="tooltip"]')?.textContent??'',/Answer 0/);
key(document.activeElement!,'Escape');await delay(10);assert.equal(document.querySelector('[role="tooltip"]'),null);
const readingAnchor=()=>{
  const row=Array.from(document.querySelectorAll<HTMLElement>('.timeline-row')).find(row=>Number(/translateY\(([-\d.]+)px\)/.exec(row.style.transform)?.[1])+row.offsetHeight>timeline.scrollTop)!;
  return {id:row.dataset.itemId,offset:timeline.scrollTop-Number(/translateY\(([-\d.]+)px\)/.exec(row.style.transform)?.[1])};
};
const previousReading=readingAnchor();
(document.activeElement as HTMLButtonElement).click();await delay(60);
assert.equal(timeline.scrollTop,0);
const before=timeline.scrollTop;
await render([...rows.slice(0,-1),{...rows.at(-1)!,text:'Streaming update '+ 'x'.repeat(500)}]);
assert.equal(document.querySelector('.timeline'),timeline,'streaming does not remount');assert.equal(timeline.scrollTop,before,'tail updates do not steal navigation position');
assert.equal(document.querySelector('[aria-label="Back to previous reading position"]')?.hasAttribute('disabled'),false);
(document.querySelector('[aria-label="Back to previous reading position"]') as HTMLButtonElement).click();await delay(60);
assert.deepEqual(readingAnchor(),previousReading,'Back restores anchor plus offset even when row measurement changes absolute position');
(document.querySelector('[aria-label="Go to latest conversation activity"]') as HTMLButtonElement).click();await delay(30);
assert.ok(timeline.scrollTop>0);
await render([{...rows[0],id:'other',chatId:'two',text:'Second chat only'}],'two');
assert.equal(document.querySelectorAll('.turn-tick').length,1);assert.match(document.querySelector('.turn-tick')?.getAttribute('aria-label')??'',/Second chat only/);
assert.equal(document.querySelector('[aria-label="Back to previous reading position"]')?.hasAttribute('disabled'),true);
// All turns remain keyboard-reachable without rendering thousands of buttons.
const many=summarizeTurns(Array.from({length:5000},(_,index)=>({...rows[0],id:'many'+index,text:'Prompt '+index})));
let chosen='';root.render(<TimelineNavigation turns={many} currentId="many0" canGoBack={false} onTurn={id=>{chosen=id;}} onBack={()=>{}} onLatest={()=>{}}/>);await delay(30);
key(document.querySelector('.turn-tick[tabindex="0"]')!,'End');await delay(30);
assert.equal(document.activeElement?.getAttribute('aria-label'),'Turn 5000: Prompt 4999');
(document.activeElement as HTMLButtonElement).click();assert.equal(chosen,'many4999');assert.ok(document.querySelectorAll('.turn-tick').length<=33);
root.unmount();assert.deepEqual(errors,[]);console.log('Timeline DOM checks passed: anchors, keyboard/preview/Escape, jump/back/latest, stream continuity, chat switch, bounded long history.');
