import type { Commands } from '../shared/protocol.ts';

/** Runtime allowlist mirroring the keys of the parent-owned `Commands` interface.
 *  `satisfies` keeps it in lockstep: protocol drift breaks typecheck here. */
const COMMANDS = {
  'app.snapshot': true,
  'computer.inspect': true,
  'computer.start': true,
  'computer.stop': true,
  'computer.destroy': true,
  'computer.exec': true,
  'computer.execution': true,
  'computer.cancel': true,
  'processes.summary': true,
  'processes.start': true,
  'processes.list': true,
  'processes.attach': true,
  'processes.detach': true,
  'processes.stop': true,

  'browser.open': true,
  'browser.navigate': true,
  'browser.back': true,
  'browser.forward': true,
  'browser.reload': true,
  'browser.stop': true,
  'browser.status': true,
  'browser.position': true,
  'browser.hide': true,
  'browser.close': true,

  'folder.add': true,
  'folder.pick': true,
  'chat.create': true,
  'chat.select': true,
  'chat.timeline': true,
  'chat.update': true,
  'chat.setPermissionMode': true,
  'chat.selectProvider': true,
  'chat.movePin': true,
  'chat.send': true,
  'chat.stop': true,
  'chat.reconcile': true,
  'chat.contextTelemetry': true,
  'approval.respond': true,
  'question.respond': true,
  'project.create': true,
  'workspace.watch': true,
  'files.list': true,
  'files.create': true,
  'files.move': true,
  'files.trash': true,
  'files.reveal': true,
  'files.search': true,
  'files.read': true,
  'files.asset': true,
  'files.nativeAvailable': true,
  'files.nativeShow': true,
  'files.nativePosition': true,
  'files.nativeHide': true,
  'files.document': true,
  'files.workbook': true,
  'files.annotations.list': true,
  'files.annotations.add': true,
  'files.annotations.remove': true,
  'git.changes': true,
  'git.status': true,
  'git.mutate': true,
  'link.open': true,
  'clipboard.write': true,
  'git.diff': true,
  'providers.list': true,
  'providers.reveal': true,
  'providers.save': true,
  'providers.remove': true,
  'providers.check': true,
  'providers.cancelCheck': true,
  'plugins.list': true,
  'plugins.inventory': true,
  'memory.list': true,
  'memory.add': true,
  'memory.search': true,
  'memory.inspect': true,
  'hindsight.status': true,
  'hindsight.retain': true,
  'hindsight.recall': true,
  'hindsight.reflect': true,
} as const satisfies Record<keyof Commands, true>;

export type CommandName = keyof typeof COMMANDS;

// Type guard: preserves narrowing for untrusted IPC channel strings.
export function isCommandName(value: unknown): value is CommandName {
  return typeof value === 'string' && Object.hasOwn(COMMANDS, value);
}
