import type { Commands } from '../shared/protocol.ts';
import { DOMAIN_COMMANDS } from '../shared/domains/index.ts';
import { PROCESS_COMMANDS } from '../shared/process-protocol.ts';
import { BROWSER_COMMANDS } from '../shared/browser-protocol.ts';
import { SCOPED_COMPUTER_COMMANDS } from '../shared/scoped-computer-protocol.ts';

/** Runtime allowlist mirroring the keys of the parent-owned `Commands` interface.
 *  `satisfies` keeps it in lockstep: protocol drift breaks typecheck here. */
const COMMANDS = {
  ...DOMAIN_COMMANDS,
  ...PROCESS_COMMANDS,
  ...BROWSER_COMMANDS,
  ...SCOPED_COMPUTER_COMMANDS,
  'app.snapshot': true,
  'updates.status': true,
  'updates.check': true,
  'updates.setAutoCheck': true,
  'updates.install': true,
  'folder.add': true,
  'folder.pick': true,
  'chat.create': true,
  'chat.select': true,
  'chat.contextMenu': true,
  'folder.contextMenu': true,
  'project.contextMenu': true,
  'folder.remove': true,
  'folder.rename': true,
  'folder.relink': true,
  'chat.delete': true,
  'chat.markUnread': true,
  'chat.export': true,
  'chat.timeline': true,
  'chat.search': true,
  'chat.editOwners': true,
  'chat.update': true,
  'chat.setPermissionMode': true,
  'chat.selectProvider': true,
  'chat.movePin': true,
  'chat.reorderPins': true,
  'chat.snooze': true,
  'chat.wake': true,
  'folder.move': true,
  'folder.reorder': true,
  'chat.send': true,
  'chat.queue.add': true,
  'chat.queue.update': true,
  'chat.queue.remove': true,
  'chat.queue.move': true,
  'chat.queue.reorder': true,
  'chat.queue.resume': true,
  'chat.queue.clear': true,
  'chat.queue.steer': true,
  'chat.steer': true,
  'attachments.stage': true,
  'attachments.discard': true,
  'attachments.list': true,
  'attachments.preview': true,
  'attachments.info': true,
  'attachments.read': true,
  'attachments.asset': true,
  'attachments.document': true,
  'attachments.workbook': true,
  'chat.fork': true,
  'chat.editOptions': true,
  'chat.editRestorePreview': true,
  'chat.editResend': true,
  'chat.retry': true,
  'chat.stop': true,
  'chat.reconcile': true,
  'chat.contextTelemetry': true,
  'approval.respond': true,
  'question.respond': true,
  'question.dismiss': true,
  'chat.compact': true,
  'project.create': true,
  'project.tasks.list': true,
  'project.tasks.create': true,
  'project.tasks.start': true,
  'project.tasks.updateStatus': true,
  'project.tasks.addEvidence': true,
  'project.decisions.list': true,
  'project.decisions.create': true,
  'project.decisions.supersede': true,
  'project.activity.list': true,
  'project.export': true,
  'project.export.file': true,
  'chat.export.file': true,
  'workspace.watch': true,
  'files.list': true,
  'files.create': true,
  'files.move': true,
  'files.trash': true,
  'files.reveal': true,
  'files.saveCopy': true,
  'files.search': true,
  'files.read': true,
  'files.asset': true,
  'files.nativeAvailable': true,
  'files.nativeShow': true,
  'files.nativePosition': true,
  'files.nativeHide': true,
  'files.document': true,
  'files.workbook': true,
  'files.annotations.list': true,
  'files.annotations.add': true,
  'files.annotations.remove': true,
  'git.changes': true,
  'git.status': true,
  'git.mutate': true,
  'git.push': true,
  'git.pullRequests': true,
  'git.compareUrl': true,
  'link.open': true,
  'clipboard.write': true,
  'git.diff': true,
  'providers.list': true,
  'providers.reveal': true,
  'providers.save': true,
  'providers.remove': true,
  'providers.check': true,
  'providers.cancelCheck': true,
  'plugins.list': true,
  'plugins.inventory': true,
  'skills.create': true,
  'memory.list': true,
  'memory.add': true,
  'memory.search': true,
  'memory.inspect': true,
  'hindsight.status': true,
  'hindsight.retain': true,
  'hindsight.recall': true,
  'hindsight.reflect': true,
} as const satisfies Record<keyof Commands, true>;

export type CommandName = keyof typeof COMMANDS;

// Type guard: preserves narrowing for untrusted IPC channel strings.
export function isCommandName(value: unknown): value is CommandName {
  return typeof value === 'string' && Object.hasOwn(COMMANDS, value);
}
