import { DatabaseSync } from 'node:sqlite';
import { chmodSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { createHash, randomUUID } from 'node:crypto';
import type { ChatPermissionMode, Folder, Project, ProjectChatReference, TaskStatus } from '../shared/protocol.ts';
import { LEGACY_STATUS, TASK_STATES, type AttemptStatus, type ProjectInstructions, type ProjectTaskRecord, type SchedulerSettings, type TaskAttempt, type TaskEdit, type TaskOwner, type TaskPriority, type TaskState, type TaskVerification, type VerificationKind } from '../shared/domains/projects-protocol.ts';

export type { TaskStatus };
export type ProjectTask = ProjectTaskRecord;
export interface ProjectDecision {id:string;projectId:string;title:string;rationale:string;author:string;scope:string;relatedTaskIds:string[];status:'active'|'superseded';supersededById:string|null;createdAt:string;updatedAt:string}
export interface ProjectActivity {id:string;projectId:string;actor:string;kind:string;summary:string;refId:string|null;createdAt:string}
export interface BoundedList<T> {items:T[];truncated:boolean}
export interface ProjectExport {schemaVersion:2;exportedAt:string;project:Project;folders:Folder[];chats:BoundedList<ProjectChatReference>;tasks:BoundedList<ProjectTask>;decisions:BoundedList<ProjectDecision>;activity:BoundedList<ProjectActivity>}
/** Who performed a write. The activity feed names them; 'user' is the person at the keyboard. */
export type Actor = 'user'|'agent'|'system'|'scheduler'|'coordinator';

const MAX_ROWS=200, MAX_EVIDENCE=50, MAX_EVIDENCE_TOTAL=50_000, MAX_DEPS=50, MAX_ATTEMPTS=20, MAX_ARTIFACTS=50;
const MODES:readonly ChatPermissionMode[]=['read-only','workspace','full'];
const now=()=>new Date().toISOString();
const parse=(v:unknown):string[]=>{try{const r=JSON.parse(String(v));return Array.isArray(r)&&r.every(x=>typeof x==='string')?r:[]}catch{return[]}};
const parseVerification=(v:unknown):TaskVerification|null=>{if(typeof v!=='string')return null;try{const r=JSON.parse(v);return r&&typeof r==='object'&&typeof r.kind==='string'?r as TaskVerification:null}catch{return null}};
function bounded<T>(rows:T[],limit:number):BoundedList<T>{return {items:rows.slice(0,limit),truncated:rows.length>limit}}
const stateOf=(v:unknown):TaskState=>TASK_STATES.includes(v as TaskState)?v as TaskState:'todo';
function attempt(r:Record<string,unknown>):TaskAttempt{return {id:String(r.id),chatId:String(r.chat_id),runId:typeof r.run_id==='string'?r.run_id:null,trigger:(r.trigger as TaskAttempt['trigger'])??'user',startedAt:String(r.started_at),endedAt:typeof r.ended_at==='string'?r.ended_at:null,status:r.status as AttemptStatus,contextVersion:typeof r.context_version==='number'?r.context_version:r.context_version==null?null:Number(r.context_version),...(typeof r.error==='string'?{error:r.error}:{})}}
function decision(r:Record<string,unknown>):ProjectDecision{return {id:String(r.id),projectId:String(r.project_id),title:String(r.title),rationale:String(r.rationale),author:String(r.author),scope:String(r.scope),relatedTaskIds:parse(r.related_task_ids),status:r.status as ProjectDecision['status'],supersededById:typeof r.superseded_by_id==='string'?r.superseded_by_id:null,createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
function activity(r:Record<string,unknown>):ProjectActivity{return {id:String(r.id),projectId:String(r.project_id),actor:String(r.actor),kind:String(r.kind),summary:String(r.summary),refId:typeof r.ref_id==='string'?r.ref_id:null,createdAt:String(r.created_at)}}
const SCHEMA=`CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'todo',dependencies TEXT NOT NULL DEFAULT '[]',acceptance TEXT NOT NULL DEFAULT '',evidence TEXT NOT NULL DEFAULT '[]',revision INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,run_chat_id TEXT,run_request_id TEXT,run_error TEXT);CREATE INDEX IF NOT EXISTS tasks_project ON tasks(project_id,created_at);CREATE TABLE IF NOT EXISTS decisions(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,title TEXT NOT NULL,rationale TEXT NOT NULL DEFAULT '',author TEXT NOT NULL,scope TEXT NOT NULL DEFAULT '',related_task_ids TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'active',superseded_by_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS decisions_project ON decisions(project_id,created_at);CREATE TABLE IF NOT EXISTS activity(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,actor TEXT NOT NULL,kind TEXT NOT NULL,summary TEXT NOT NULL,ref_id TEXT,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS activity_project ON activity(project_id,created_at);CREATE TABLE IF NOT EXISTS suspended_projects(project_id TEXT PRIMARY KEY,suspended_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS attempts(id TEXT PRIMARY KEY,task_id TEXT NOT NULL,project_id TEXT NOT NULL,chat_id TEXT NOT NULL,run_id TEXT,trigger TEXT NOT NULL DEFAULT 'user',started_at TEXT NOT NULL,ended_at TEXT,status TEXT NOT NULL,context_version INTEGER,error TEXT);CREATE INDEX IF NOT EXISTS attempts_task ON attempts(task_id,started_at);CREATE INDEX IF NOT EXISTS attempts_chat ON attempts(chat_id,status);
CREATE TABLE IF NOT EXISTS schedules(project_id TEXT PRIMARY KEY,auto_dispatch INTEGER NOT NULL DEFAULT 0,paused INTEGER NOT NULL DEFAULT 0,concurrency INTEGER NOT NULL DEFAULT 2,budget_minutes INTEGER NOT NULL DEFAULT 30,permission_mode TEXT NOT NULL DEFAULT 'workspace',updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS leases(task_id TEXT PRIMARY KEY,project_id TEXT NOT NULL,holder TEXT NOT NULL,expires_at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS instructions(project_id TEXT NOT NULL,version INTEGER NOT NULL,text TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(project_id,version));
CREATE TABLE IF NOT EXISTS goal_versions(project_id TEXT NOT NULL,version INTEGER NOT NULL,goal TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(project_id,version));
CREATE TABLE IF NOT EXISTS context_packets(project_id TEXT NOT NULL,version INTEGER NOT NULL,hash TEXT NOT NULL,created_at TEXT NOT NULL,PRIMARY KEY(project_id,version));
CREATE TABLE IF NOT EXISTS coordinators(project_id TEXT PRIMARY KEY,chat_id TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS coordinator_marks(project_id TEXT NOT NULL,key TEXT NOT NULL,state TEXT NOT NULL,error TEXT,created_at TEXT NOT NULL,PRIMARY KEY(project_id,key));`;
const TASK_COLUMNS=[['run_chat_id','TEXT'],['run_request_id','TEXT'],['run_error','TEXT'],['owner_kind',"TEXT NOT NULL DEFAULT 'agent'"],['owner_id',"TEXT NOT NULL DEFAULT 'agent'"],['priority','INTEGER NOT NULL DEFAULT 2'],['artifacts',"TEXT NOT NULL DEFAULT '[]'"],['verification','TEXT'],['permission_mode','TEXT'],['budget_minutes','INTEGER'],['blocked_by','TEXT']] as const;
/** SQL twin of activityCategory() in project-team-protocol.ts. */
export const ACTIVITY_CATEGORY_SQL="CASE WHEN kind LIKE 'task.run-%' OR kind IN ('task.budget-exceeded','task.needs-input') THEN 'runs' WHEN kind LIKE 'task.%' THEN 'tasks' WHEN kind LIKE 'decision.%' THEN 'decisions' WHEN kind LIKE 'coordinator.%' OR kind='project.coordinator' THEN 'coordinator' WHEN kind LIKE 'memory.%' THEN 'memory' WHEN kind LIKE 'environment.%' THEN 'environment' WHEN kind LIKE 'chat.%' THEN 'chats' WHEN kind LIKE 'member.%' THEN 'members' ELSE 'project' END";
const STALE='Stale write — task was modified. Refresh and retry.';

export class ProjectTaskStore {
 private db:DatabaseSync;
 private depth=0;
 constructor(dataDir:string){mkdirSync(dataDir,{recursive:true,mode:0o700});const file=join(dataDir,'muster-project-tasks.sqlite');this.db=new DatabaseSync(file);chmodSync(file,0o600);this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=3000;');this.db.exec(SCHEMA);const columns=this.db.prepare("SELECT name FROM pragma_table_info('tasks')").all() as {name:string}[];for(const [name,definition] of TASK_COLUMNS)if(!columns.some(c=>c.name===name))this.db.exec(`ALTER TABLE tasks ADD COLUMN ${name} ${definition}`)}
 /** Re-entrant: nested calls join the outer transaction, so multi-step writes (coordinator batches) commit or roll back together. */
 tx<T>(fn:()=>T):T{if(this.depth)return fn();this.db.exec('BEGIN IMMEDIATE');this.depth++;try{const v=fn();this.db.exec('COMMIT');return v}catch(e){this.db.exec('ROLLBACK');throw e}finally{this.depth--}}
 private lastActivityAt='';
 // Strictly increasing timestamps: two events in the same millisecond still list in the order they happened
 // (created_at breaks ties before the random id in every activity query and cursor).
 private activityTime():string{let at=now();if(at<=this.lastActivityAt)at=new Date(Date.parse(this.lastActivityAt)+1).toISOString();this.lastActivityAt=at;return at;}
 private log(projectId:string,actor:string,kind:string,summary:string,refId:string|null){this.db.prepare('INSERT INTO activity VALUES(?,?,?,?,?,?,?)').run(randomUUID(),projectId,actor,kind,summary.slice(0,1024),refId,this.activityTime())}
 private attemptsFor(taskId:string):TaskAttempt[]{return (this.db.prepare('SELECT * FROM attempts WHERE task_id=? ORDER BY started_at DESC,id DESC LIMIT ?').all(taskId,MAX_ATTEMPTS) as Record<string,unknown>[]).map(attempt)}
 private task(r:Record<string,unknown>,attempts?:TaskAttempt[]):ProjectTask{const state=stateOf(r.status),priority=Number(r.priority??2);return {id:String(r.id),projectId:String(r.project_id),title:String(r.title),status:LEGACY_STATUS[state],state,dependencies:parse(r.dependencies),acceptance:String(r.acceptance),evidence:parse(r.evidence),...(typeof r.run_chat_id==='string'?{runChatId:r.run_chat_id}:{}),...(typeof r.run_request_id==='string'?{runRequestId:r.run_request_id}:{}),...(typeof r.run_error==='string'?{runError:r.run_error}:{}),revision:Number(r.revision),createdAt:String(r.created_at),updatedAt:String(r.updated_at),owner:{kind:r.owner_kind==='user'?'user':'agent',id:String(r.owner_id??'agent')},priority:(priority>=0&&priority<=3?priority:2) as TaskPriority,artifacts:parse(r.artifacts),attempts:attempts??this.attemptsFor(String(r.id)),verification:parseVerification(r.verification),permissionMode:MODES.includes(r.permission_mode as ChatPermissionMode)?r.permission_mode as ChatPermissionMode:null,budgetMinutes:typeof r.budget_minutes==='number'||typeof r.budget_minutes==='bigint'?Number(r.budget_minutes):null,blockedBy:typeof r.blocked_by==='string'?r.blocked_by:null}}
 private write(t:ProjectTask,patch:Record<string,string|number|null>):void{const cols=Object.keys(patch);this.db.prepare(`UPDATE tasks SET ${cols.map(c=>`${c}=?`).join(',')},revision=revision+1,updated_at=? WHERE id=?`).run(...cols.map(c=>patch[c]!),now(),t.id)}
 getTask(id:string):ProjectTask|undefined{const r=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?this.task(r):undefined}
 private fresh(id:string):ProjectTask{return this.getTask(id)!}
 getDecision(id:string):ProjectDecision|undefined{const r=this.db.prepare('SELECT * FROM decisions WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?decision(r):undefined}
 assertTaskProject(projectId:string,id:string):ProjectTask{const t=this.getTask(id);if(!t)throw Error('Task not found.');if(t.projectId!==projectId)throw Error('Task belongs to a different project.');return t}
 assertDecisionProject(projectId:string,id:string):ProjectDecision{const d=this.getDecision(id);if(!d)throw Error('Decision not found.');if(d.projectId!==projectId)throw Error('Decision belongs to a different project.');return d}
 listTasks(projectId:string):BoundedList<ProjectTask>{const rows=this.db.prepare('SELECT * FROM tasks WHERE project_id=? ORDER BY created_at,id LIMIT ?').all(projectId,MAX_ROWS+1) as Record<string,unknown>[];const byTask=new Map<string,TaskAttempt[]>();for(const r of this.db.prepare('SELECT * FROM (SELECT *,ROW_NUMBER() OVER (PARTITION BY task_id ORDER BY started_at DESC,id DESC) AS n FROM attempts WHERE project_id=?) WHERE n<=?').all(projectId,MAX_ATTEMPTS) as Record<string,unknown>[]){const list=byTask.get(String(r.task_id))??[];list.push(attempt(r));byTask.set(String(r.task_id),list)}return bounded(rows.map(r=>this.task(r,byTask.get(String(r.id))??[])),MAX_ROWS)}
 listRunningTasks():ProjectTask[]{return (this.db.prepare("SELECT * FROM tasks WHERE status IN ('running','needs-input') ORDER BY updated_at LIMIT 1000").all() as Record<string,unknown>[]).map(r=>this.task(r))}
 /** Task whose current run lives in this chat, if any. */
 taskForChat(chatId:string):ProjectTask|undefined{const r=this.db.prepare("SELECT * FROM tasks WHERE run_chat_id=? AND status IN ('running','needs-input') LIMIT 1").get(chatId) as Record<string,unknown>|undefined;return r?this.task(r):undefined}
 /** Latest task linked to this chat, whatever its state. */
 taskByRunChat(chatId:string):ProjectTask|undefined{const r=this.db.prepare('SELECT * FROM tasks WHERE run_chat_id=? ORDER BY updated_at DESC LIMIT 1').get(chatId) as Record<string,unknown>|undefined;return r?this.task(r):undefined}
 /** Projects whose scheduler is on and not paused. */
 autoProjects():string[]{return (this.db.prepare('SELECT project_id FROM schedules WHERE auto_dispatch=1 AND paused=0').all() as {project_id:string}[]).map(r=>r.project_id)}
 recoverUnlinkedRuns():ProjectTask[]{return this.tx(()=>{const rows=this.db.prepare("SELECT * FROM tasks WHERE status IN ('running','needs-input') AND run_request_id IS NOT NULL AND run_chat_id IS NULL LIMIT 1000").all() as Record<string,unknown>[];return rows.map(row=>{const t=this.task(row),reason='The app stopped before this task could be linked to its agent chat. Review the Project activity, then reopen the task before starting again.';this.write(t,{status:'blocked',run_error:reason});this.log(t.projectId,'system','task.run-recovered',reason,t.id);return this.fresh(t.id)})})}
 listDecisions(projectId:string):BoundedList<ProjectDecision>{const rows=this.db.prepare('SELECT * FROM decisions WHERE project_id=? ORDER BY created_at,id LIMIT ?').all(projectId,MAX_ROWS+1) as Record<string,unknown>[];return bounded(rows.map(decision),MAX_ROWS)}
 /** PRJ-11: filtered, keyset-paged activity. Categories use ACTIVITY_CATEGORY_SQL, the SQL twin of activityCategory(). */
 queryActivity(projectId:string,q:{categories?:string[];actors?:string[];since?:string|null;before?:{createdAt:string;id:string}|null;limit?:number}):BoundedList<ProjectActivity>&{actors:string[]}{const cap=Math.max(1,Math.min(200,Math.floor(q.limit??100)));const where=['project_id=?'],args:(string|number)[]=[projectId];if(q.categories?.length){where.push(`(${ACTIVITY_CATEGORY_SQL}) IN (${q.categories.map(()=>'?').join(',')})`);args.push(...q.categories)}if(q.actors?.length){where.push(`actor IN (${q.actors.map(()=>'?').join(',')})`);args.push(...q.actors)}if(q.since){where.push('created_at>=?');args.push(q.since)}if(q.before){where.push('(created_at<? OR (created_at=? AND id<?))');args.push(q.before.createdAt,q.before.createdAt,q.before.id)}const rows=this.db.prepare(`SELECT * FROM activity WHERE ${where.join(' AND ')} ORDER BY created_at DESC,id DESC LIMIT ?`).all(...args,cap+1) as Record<string,unknown>[];const actors=(this.db.prepare('SELECT DISTINCT actor FROM activity WHERE project_id=? ORDER BY actor').all(projectId) as {actor:string}[]).map(r=>r.actor);return {...bounded(rows.map(activity),cap),actors}}
 listActivity(projectId:string,limit=100):BoundedList<ProjectActivity>{const cap=Math.max(1,Math.min(200,Math.floor(limit)));const rows=this.db.prepare('SELECT * FROM activity WHERE project_id=? ORDER BY created_at DESC,id DESC LIMIT ?').all(projectId,cap+1) as Record<string,unknown>[];return bounded(rows.map(activity),cap)}
 private validateDeps(projectId:string,taskId:string|null,deps:string[]){if(deps.length>MAX_DEPS)throw Error('Too many dependencies (max 50).');const seen=new Set<string>();for(const depId of deps){if(seen.has(depId))throw Error('Duplicate dependency.');seen.add(depId);if(depId===taskId)throw Error('A task cannot depend on itself.');const dep=this.getTask(depId);if(!dep)throw Error(`Dependency not found: ${depId}`);if(dep.projectId!==projectId)throw Error('Dependencies must belong to this project.')}if(taskId){const visited=new Set<string>(),queue=[...deps];while(queue.length){const id=queue.pop()!;if(id===taskId)throw Error('Dependency would create a cycle.');if(visited.has(id))continue;visited.add(id);const t=this.getTask(id);if(t){if(t.projectId!==projectId)throw Error('Dependency graph crosses project boundary.');queue.push(...t.dependencies)}}}}
 private validateFields(e:TaskEdit){if(e.title!==undefined&&(!e.title.trim()||e.title.length>500))throw Error('Task title required (max 500 characters).');if(e.acceptance!==undefined&&e.acceptance.length>4000)throw Error('Acceptance criteria exceed 4,000 characters.');if(e.priority!==undefined&&![0,1,2,3].includes(e.priority))throw Error('Invalid priority.');if(e.owner!==undefined&&((e.owner.kind!=='user'&&e.owner.kind!=='agent')||!e.owner.id||e.owner.id.length>128))throw Error('Invalid owner.');if(e.artifacts!==undefined&&(e.artifacts.length>MAX_ARTIFACTS||e.artifacts.some(a=>!a.trim()||a.length>1000)))throw Error('Artifacts: up to 50 references of 1,000 characters.');if(e.permissionMode!=null&&!MODES.includes(e.permissionMode))throw Error('Invalid permission mode.');if(e.budgetMinutes!=null&&(!Number.isSafeInteger(e.budgetMinutes)||e.budgetMinutes<1||e.budgetMinutes>1440))throw Error('Run budget must be 1–1,440 minutes.')}
 createTask(i:{projectId:string;title:string;acceptance:string;dependencies:string[];owner?:TaskOwner;priority?:TaskPriority;permissionMode?:ChatPermissionMode|null;budgetMinutes?:number|null},actor:Actor='user'):ProjectTask{const title=i.title.trim();if(!title)throw Error('Task title required.');if(title.length>500||i.acceptance.length>4000)throw Error('Task fields are invalid or exceed their limits.');this.validateFields({...(i.owner?{owner:i.owner}:{}),...(i.priority!==undefined?{priority:i.priority}:{}),...(i.permissionMode!==undefined?{permissionMode:i.permissionMode}:{}),...(i.budgetMinutes!==undefined?{budgetMinutes:i.budgetMinutes}:{})});const deps=[...new Set(i.dependencies)],taskId=randomUUID(),owner=i.owner??{kind:'agent',id:'agent'};return this.tx(()=>{this.validateDeps(i.projectId,taskId,deps);const ts=now();this.db.prepare('INSERT INTO tasks(id,project_id,title,status,dependencies,acceptance,evidence,revision,created_at,updated_at,owner_kind,owner_id,priority,artifacts,permission_mode,budget_minutes) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(taskId,i.projectId,title,'todo',JSON.stringify(deps),i.acceptance,'[]',0,ts,ts,owner.kind,owner.id,i.priority??2,'[]',i.permissionMode??null,i.budgetMinutes??null);this.log(i.projectId,actor,'task.create',`Created task: ${title}`,taskId);return this.fresh(taskId)})}
 /** Edits fields and dependencies. A dependency change is re-validated for cycles and project boundaries. */
 editTask(i:{projectId:string;id:string;revision:number;patch:TaskEdit},actor:Actor='user'):ProjectTask{this.validateFields(i.patch);return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.revision!==i.revision)throw Error(STALE);const p=i.patch,set:Record<string,string|number|null>={},changes:string[]=[];
  if(p.title!==undefined&&p.title.trim()!==t.title){set.title=p.title.trim();changes.push('title')}
  if(p.acceptance!==undefined&&p.acceptance!==t.acceptance){set.acceptance=p.acceptance;changes.push('acceptance')}
  if(p.priority!==undefined&&p.priority!==t.priority){set.priority=p.priority;changes.push('priority')}
  if(p.owner&&(p.owner.kind!==t.owner.kind||p.owner.id!==t.owner.id)){set.owner_kind=p.owner.kind;set.owner_id=p.owner.id;changes.push('owner')}
  if(p.artifacts!==undefined){const a=[...new Set(p.artifacts.map(s=>s.trim()))];if(JSON.stringify(a)!==JSON.stringify(t.artifacts)){set.artifacts=JSON.stringify(a);changes.push('artifacts')}}
  if(p.permissionMode!==undefined&&p.permissionMode!==t.permissionMode){set.permission_mode=p.permissionMode;changes.push('access')}
  if(p.budgetMinutes!==undefined&&p.budgetMinutes!==t.budgetMinutes){set.budget_minutes=p.budgetMinutes;changes.push('run budget')}
  if(p.dependencies!==undefined){const deps=[...new Set(p.dependencies)];if(JSON.stringify(deps)!==JSON.stringify(t.dependencies)){this.validateDeps(i.projectId,t.id,deps);set.dependencies=JSON.stringify(deps);changes.push('dependencies');if(t.blockedBy&&!deps.includes(t.blockedBy)&&t.state==='blocked'){set.status='todo';set.blocked_by=null;set.run_error=null}}}
  if(!changes.length)return t;this.write(t,set);this.log(i.projectId,actor,'task.edit',`Edited "${String(set.title??t.title)}": ${changes.join(', ')}`,t.id);return this.fresh(t.id)})}
 deleteTask(i:{projectId:string;id:string;revision:number},actor:Actor='user'):void{this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.revision!==i.revision)throw Error(STALE);if(t.state==='running'||t.state==='needs-input')throw Error('Stop the agent run before deleting this task.');const dependent=(this.db.prepare('SELECT title,dependencies FROM tasks WHERE project_id=?').all(i.projectId) as {title:string;dependencies:string}[]).find(r=>parse(r.dependencies).includes(t.id));if(dependent)throw Error(`"${dependent.title}" depends on this task. Remove that dependency first.`);this.db.prepare('DELETE FROM tasks WHERE id=?').run(t.id);this.db.prepare('DELETE FROM attempts WHERE task_id=?').run(t.id);this.db.prepare('DELETE FROM leases WHERE task_id=?').run(t.id);this.log(i.projectId,actor,'task.delete',`Deleted task: ${t.title}`,null)})}
 assertCanStartTask(i:{projectId:string;id:string;revision:number}):ProjectTask{const t=this.assertTaskProject(i.projectId,i.id);if(this.isSuspended(i.projectId))throw Error('This Project is archived. Restore it before starting tasks.');if(t.state==='running'||t.state==='needs-input')throw Error('This task already has an active run. Open its linked chat.');if(t.revision!==i.revision)throw Error(STALE);if(t.state!=='todo'&&t.state!=='blocked'&&t.state!=='failed')throw Error('Reopen this task before starting another run.');for(const depId of t.dependencies){const dep=this.assertTaskProject(i.projectId,depId);if(dep.state!=='verified')throw Error(`Dependency "${dep.title}" is not yet verified.`)}return t}
 startTask(i:{projectId:string;id:string;revision:number;requestId:string;chatId:string},actor:Actor='user'):ProjectTask{return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.runRequestId===i.requestId&&t.runChatId)return t;this.assertCanStartTask(i);this.write(t,{status:'running',run_chat_id:i.chatId,run_request_id:i.requestId,run_error:null,blocked_by:null});this.log(i.projectId,actor,'task.run-started',`Started "${t.title}" in an agent chat`,i.chatId);return this.fresh(t.id)})}
 failTaskStart(i:{projectId:string;id:string;requestId:string;chatId:string;reason:string}):ProjectTask|undefined{return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.runRequestId!==i.requestId||t.runChatId!==i.chatId||(t.state!=='running'&&t.state!=='needs-input'))return undefined;const reason=i.reason.slice(0,2000);this.write(t,{status:'blocked',run_error:reason});this.closeAttempts(i.chatId,'failed',reason);this.log(i.projectId,'system','task.run-failed',`Could not dispatch "${t.title}": ${reason}`,i.chatId);return this.fresh(t.id)})}
 /** A finished run: completed → implemented, failed → failed, interrupted → blocked. Verification stays a separate human step. */
 settleRunForChat(chatId:string,status:'completed'|'failed'|'interrupted',error?:string):ProjectTask|undefined{return this.tx(()=>{const t=this.taskForChat(chatId);if(!t)return;const next:TaskState=status==='completed'?'implemented':status==='failed'?'failed':'blocked',reason=status==='completed'?null:(error||`Agent run ${status}. Open the linked chat to review or recover it.`).slice(0,2000);this.write(t,{status:next,run_error:reason});this.closeAttempts(chatId,status,reason??undefined);this.log(t.projectId,'agent',`task.run-${next}`,`Agent work for "${t.title}" ${status==='completed'?'finished; review and verify it':status==='failed'?'failed':'stopped'}.`,chatId);return this.fresh(t.id)})}
 /** A pending approval or question in the task's live chat moves it to needs-input; answering it moves it back to running. */
 markNeedsInput(chatId:string,waiting:boolean):ProjectTask|undefined{return this.tx(()=>{const t=this.taskForChat(chatId);if(!t||(t.state==='needs-input')===waiting)return undefined;this.write(t,{status:waiting?'needs-input':'running'});if(waiting)this.log(t.projectId,'agent','task.needs-input',`"${t.title}" is waiting for your answer`,chatId);return this.fresh(t.id)})}
 /** Legacy five-state setter kept for the service command. */
 updateTaskStatus(i:{projectId:string;id:string;status:TaskStatus;evidence?:string[];revision:number}):ProjectTask{if(!['todo','running','blocked','implemented','verified'].includes(i.status))throw Error('Invalid task status.');if(i.status==='running')throw Error('Start this task in an agent chat; running status is set only by a real agent run.');if(i.status==='verified'){const notes=(i.evidence??[]).map(s=>s.trim()).filter(Boolean);if(!notes.length)throw Error('Verification requires at least one evidence entry.');if(notes.length>MAX_EVIDENCE||notes.some(s=>s.length>2000))throw Error('Evidence exceeds the limit of 50 entries (2,000 characters each).');return this.verifyTask({projectId:i.projectId,id:i.id,revision:i.revision,kind:'manual',notes:notes.join('\n'),evidence:notes})}return this.setState({projectId:i.projectId,id:i.id,revision:i.revision,state:i.status})}
 /** Manual transitions. Reopening a verified task re-blocks dependents that were waiting to start. */
 setState(i:{projectId:string;id:string;revision:number;state:TaskState;reason?:string},actor:Actor='user'):ProjectTask{if(!TASK_STATES.includes(i.state))throw Error('Invalid task status.');if(i.state==='running'||i.state==='needs-input')throw Error('Start this task in an agent chat; running status is set only by a real agent run.');if(i.state==='verified')throw Error('Record verification (tests, review or manual check) to mark a task verified.');const reason=i.reason?.trim().slice(0,2000);return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.revision!==i.revision)throw Error(STALE);if(t.state===i.state)return t;if((t.state==='running'||t.state==='needs-input')&&t.runChatId)this.closeAttempts(t.runChatId,i.state==='implemented'||i.state==='review'?'completed':'cancelled');this.write(t,{status:i.state,run_error:i.state==='blocked'||i.state==='failed'?reason||null:null,blocked_by:null,...(i.state==='todo'&&t.state==='verified'?{verification:null}:{})});this.log(i.projectId,actor,'task.status',`Task "${t.title}": ${t.state} → ${i.state}${reason?` (${reason})`:''}`,t.id);if(t.state==='verified')this.reblockDependents(t,actor);return this.fresh(t.id)})}
 private reblockDependents(dep:ProjectTask,actor:Actor){for(const row of this.db.prepare("SELECT * FROM tasks WHERE project_id=? AND status='todo'").all(dep.projectId) as Record<string,unknown>[]){const t=this.task(row);if(!t.dependencies.includes(dep.id))continue;this.write(t,{status:'blocked',blocked_by:dep.id,run_error:`Waiting on "${dep.title}", which was reopened.`});this.log(dep.projectId,actor,'task.reblocked',`"${t.title}" is blocked again: "${dep.title}" was reopened`,t.id)}}
 private unblockDependents(dep:ProjectTask){for(const row of this.db.prepare("SELECT * FROM tasks WHERE project_id=? AND status='blocked' AND blocked_by=?").all(dep.projectId,dep.id) as Record<string,unknown>[]){const t=this.task(row);this.write(t,{status:'todo',blocked_by:null,run_error:null});this.log(dep.projectId,'system','task.unblocked',`"${t.title}" can start again: "${dep.title}" is verified`,t.id)}}
 /** Structured verification. Implemented or review first; re-verifying a verified task refreshes a stale record. */
 verifyTask(i:{projectId:string;id:string;revision:number;kind:VerificationKind;notes:string;command?:string;reviewer?:string;commitSha?:string;folderId?:string;evidence?:string[]},actor:Actor='user'):ProjectTask{if(!['tests','review','manual'].includes(i.kind))throw Error('Invalid verification kind.');const notes=i.notes.trim();if(!notes)throw Error('Verification requires notes: what was checked and what it showed.');if(notes.length>4000||(i.command?.length??0)>1000||(i.reviewer?.length??0)>200)throw Error('Verification fields exceed their limits.');if(i.kind==='tests'&&!i.command?.trim())throw Error('Name the test command that passed.');if(i.kind==='review'&&!i.reviewer?.trim())throw Error('Name the reviewer.');if(i.commitSha!==undefined&&!/^[0-9a-f]{7,64}$/.test(i.commitSha))throw Error('Invalid commit.');return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.revision!==i.revision)throw Error(STALE);if(t.state!=='implemented'&&t.state!=='review'&&t.state!=='verified')throw Error('Mark the task implemented (or send it to review) before verifying it.');const v:TaskVerification={kind:i.kind,notes,verifiedAt:now(),...(i.command?.trim()?{command:i.command.trim()}:{}),...(i.reviewer?.trim()?{reviewer:i.reviewer.trim()}:{}),...(i.commitSha?{commitSha:i.commitSha}:{}),...(i.folderId?{folderId:i.folderId}:{})};const line=i.evidence??[`${i.kind==='tests'?`Tests: ${v.command}`:i.kind==='review'?`Review by ${v.reviewer}`:'Manual check'} — ${notes}${v.commitSha?` @ ${v.commitSha.slice(0,7)}`:''}`.slice(0,2000)];const evidence=[...new Set([...t.evidence,...line])];if(evidence.length>MAX_EVIDENCE||JSON.stringify(evidence).length>MAX_EVIDENCE_TOTAL)throw Error('Evidence history is full. Remove older entries before adding more.');this.write(t,{status:'verified',evidence:JSON.stringify(evidence),verification:JSON.stringify(v),run_error:null});this.log(i.projectId,actor,'task.verified',`Verified "${t.title}" (${i.kind}${v.commitSha?` at ${v.commitSha.slice(0,7)}`:''})`,t.id);const next=this.fresh(t.id);this.unblockDependents(next);return next})}
 addEvidence(i:{projectId:string;id:string;entries:string[];revision:number}):ProjectTask{return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.revision!==i.revision)throw Error(STALE);const added=i.entries.map(s=>s.trim()).filter(Boolean);if(!added.length||added.length>MAX_EVIDENCE||added.some(s=>s.length>2000))throw Error('Provide 1–50 evidence entries, each up to 2,000 characters.');const evidence=[...new Set([...t.evidence,...added])];if(evidence.length>MAX_EVIDENCE||JSON.stringify(evidence).length>MAX_EVIDENCE_TOTAL)throw Error('Evidence history is full.');this.write(t,{evidence:JSON.stringify(evidence)});this.log(i.projectId,'user','task.evidence',`Added evidence to "${t.title}"`,t.id);return this.fresh(t.id)})}
 /** Opens an attempt for the task running in this chat, once per run. */
 beginAttempt(i:{chatId:string;runId:string;trigger?:TaskAttempt['trigger'];contextVersion?:number|null}):TaskAttempt|undefined{return this.tx(()=>{const t=this.taskForChat(i.chatId);if(!t)return undefined;const existing=this.db.prepare('SELECT * FROM attempts WHERE chat_id=? AND (run_id=? OR (run_id IS NULL AND status=?)) ORDER BY started_at DESC LIMIT 1').get(i.chatId,i.runId,'running') as Record<string,unknown>|undefined;if(existing){this.db.prepare('UPDATE attempts SET run_id=?,context_version=COALESCE(?,context_version) WHERE id=?').run(i.runId,i.contextVersion??null,String(existing.id));return attempt({...existing,run_id:i.runId,context_version:i.contextVersion??existing.context_version})}const a:TaskAttempt={id:randomUUID(),chatId:i.chatId,runId:i.runId,trigger:i.trigger??'user',startedAt:now(),endedAt:null,status:'running',contextVersion:i.contextVersion??null};this.db.prepare('INSERT INTO attempts VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(a.id,t.id,t.projectId,a.chatId,a.runId,a.trigger,a.startedAt,null,'running',a.contextVersion,null);return a})}
 private closeAttempts(chatId:string,status:AttemptStatus,error?:string){this.db.prepare("UPDATE attempts SET status=?,ended_at=?,error=? WHERE chat_id=? AND status='running'").run(status,now(),error?.slice(0,2000)??null,chatId)}
 /** Running attempts with their task, oldest first, for budget enforcement. */
 openAttempts(projectId?:string):{attempt:TaskAttempt;task:ProjectTask}[]{const rows=(projectId?this.db.prepare("SELECT * FROM attempts WHERE status='running' AND project_id=? ORDER BY started_at LIMIT 500").all(projectId):this.db.prepare("SELECT * FROM attempts WHERE status='running' ORDER BY started_at LIMIT 500").all()) as Record<string,unknown>[];return rows.flatMap(r=>{const t=this.getTask(String(r.task_id));return t?[{attempt:attempt(r),task:t}]:[]})}
 /** Replaces a settled run's generic reason, e.g. with the budget that stopped it. */
 annotateRun(taskId:string,reason:string){this.tx(()=>{const t=this.getTask(taskId);if(!t)return;this.write(t,{run_error:reason.slice(0,2000)});this.db.prepare("UPDATE attempts SET error=? WHERE task_id=? AND id=(SELECT id FROM attempts WHERE task_id=? ORDER BY started_at DESC LIMIT 1)").run(reason.slice(0,2000),taskId,taskId)})}
 createDecision(i:{projectId:string;title:string;rationale:string;scope:string;relatedTaskIds:string[]},actor:Actor='user'):ProjectDecision{const title=i.title.trim();if(!title||title.length>500||i.rationale.length>8000||i.scope.length>500)throw Error('Decision fields are invalid or exceed their limits.');const taskIds=[...new Set(i.relatedTaskIds)];if(taskIds.length>MAX_DEPS)throw Error('Too many related tasks.');return this.tx(()=>{for(const id of taskIds)this.assertTaskProject(i.projectId,id);const ts=now(),d:ProjectDecision={id:randomUUID(),projectId:i.projectId,title,rationale:i.rationale,author:actor,scope:i.scope,relatedTaskIds:taskIds,status:'active',supersededById:null,createdAt:ts,updatedAt:ts};this.db.prepare('INSERT INTO decisions VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(d.id,d.projectId,d.title,d.rationale,d.author,d.scope,JSON.stringify(taskIds),d.status,null,ts,ts);this.log(i.projectId,actor,'decision.create',`Decision recorded: ${title}`,d.id);return d})}
 editDecision(i:{projectId:string;id:string;title?:string;rationale?:string;scope?:string;relatedTaskIds?:string[]},actor:Actor='user'):ProjectDecision{return this.tx(()=>{const d=this.assertDecisionProject(i.projectId,i.id);if(d.status==='superseded')throw Error('Superseded decisions are read-only. Edit the replacement instead.');const title=i.title===undefined?d.title:i.title.trim(),rationale=i.rationale??d.rationale,scope=i.scope??d.scope,related=i.relatedTaskIds===undefined?d.relatedTaskIds:[...new Set(i.relatedTaskIds)];if(!title||title.length>500||rationale.length>8000||scope.length>500||related.length>MAX_DEPS)throw Error('Decision fields are invalid or exceed their limits.');for(const id of related)this.assertTaskProject(i.projectId,id);const ts=now();this.db.prepare('UPDATE decisions SET title=?,rationale=?,scope=?,related_task_ids=?,updated_at=? WHERE id=?').run(title,rationale,scope,JSON.stringify(related),ts,d.id);this.log(i.projectId,actor,'decision.edit',`Edited decision: ${title}`,d.id);return {...d,title,rationale,scope,relatedTaskIds:related,updatedAt:ts}})}
 supersedeDecision(i:{projectId:string;id:string;replacementId:string},actor:Actor='user'):ProjectDecision{return this.tx(()=>{const old=this.assertDecisionProject(i.projectId,i.id),replacement=this.assertDecisionProject(i.projectId,i.replacementId);if(old.id===replacement.id)throw Error('A decision cannot supersede itself.');if(old.status==='superseded')throw Error('Decision is already superseded.');if(replacement.status==='superseded')throw Error('Replacement decision is already superseded.');let cursor:ProjectDecision|undefined=replacement;const seen=new Set<string>();while(cursor){if(cursor.id===old.id)throw Error('Superseding would create a decision cycle.');if(seen.has(cursor.id))throw Error('Decision supersession chain is corrupt.');seen.add(cursor.id);cursor=cursor.supersededById?this.getDecision(cursor.supersededById):undefined;}const ts=now();this.db.prepare('UPDATE decisions SET status=?,superseded_by_id=?,updated_at=? WHERE id=? AND project_id=? AND status=?').run('superseded',replacement.id,ts,old.id,i.projectId,'active');this.log(i.projectId,actor,'decision.supersede',`Decision "${old.title}" superseded by "${replacement.title}"`,old.id);return {...old,status:'superseded',supersededById:replacement.id,updatedAt:ts}})}
 exportProject(project:Project,folders:Folder[],chats:ProjectChatReference[]):ProjectExport{return {schemaVersion:2,exportedAt:now(),project,folders,chats:bounded(chats,MAX_ROWS),tasks:this.listTasks(project.id),decisions:this.listDecisions(project.id),activity:this.listActivity(project.id,200)}}
 /** Archived Projects are suspended: no task may start a new agent run until restored. */
 isSuspended(projectId:string):boolean{return Boolean(this.db.prepare('SELECT 1 FROM suspended_projects WHERE project_id=?').get(projectId))}
 setSuspended(projectId:string,suspended:boolean){if(suspended)this.db.prepare('INSERT OR IGNORE INTO suspended_projects VALUES(?,?)').run(projectId,now());else this.db.prepare('DELETE FROM suspended_projects WHERE project_id=?').run(projectId)}
 /** Exact counts plus the first 50 tasks, running first, for archive and delete previews. */
 taskImpact(projectId:string):{total:number;running:number;open:number;items:{id:string;title:string;status:TaskStatus}[]}{const count=(where:string)=>Number((this.db.prepare(`SELECT COUNT(*) AS n FROM tasks WHERE project_id=?${where}`).get(projectId) as {n:number}).n);const items=(this.db.prepare("SELECT id,title,status FROM tasks WHERE project_id=? ORDER BY status IN ('running','needs-input') DESC,updated_at DESC LIMIT 50").all(projectId) as {id:string;title:string;status:string}[]).map(({id,title,status})=>({id,title,status:LEGACY_STATUS[stateOf(status)]}));return {total:count(''),running:count(" AND status IN ('running','needs-input')"),open:count(" AND status IN ('todo','running','needs-input','blocked','review','failed')"),items}}
 /** Records a Project change in the activity feed. */
 record(projectId:string,kind:string,summary:string,refId:string|null=null,actor:Actor='user'){this.log(projectId,actor,kind,summary,refId)}
 schedule(projectId:string):SchedulerSettings{const r=this.db.prepare('SELECT * FROM schedules WHERE project_id=?').get(projectId) as Record<string,unknown>|undefined;return r?{autoDispatch:Boolean(r.auto_dispatch),paused:Boolean(r.paused),concurrency:Number(r.concurrency),budgetMinutes:Number(r.budget_minutes),permissionMode:MODES.includes(r.permission_mode as ChatPermissionMode)?r.permission_mode as ChatPermissionMode:'workspace',updatedAt:String(r.updated_at)}:{autoDispatch:false,paused:false,concurrency:2,budgetMinutes:30,permissionMode:'workspace',updatedAt:null}}
 setSchedule(projectId:string,patch:Partial<Omit<SchedulerSettings,'updatedAt'>>,actor:Actor='user'):SchedulerSettings{const cur=this.schedule(projectId),next={...cur,...patch};if(!Number.isSafeInteger(next.concurrency)||next.concurrency<1||next.concurrency>8)throw Error('Concurrency must be 1–8.');if(!Number.isSafeInteger(next.budgetMinutes)||next.budgetMinutes<1||next.budgetMinutes>1440)throw Error('Run budget must be 1–1,440 minutes.');if(!MODES.includes(next.permissionMode))throw Error('Invalid permission mode.');return this.tx(()=>{this.db.prepare('INSERT INTO schedules VALUES(?,?,?,?,?,?,?) ON CONFLICT(project_id) DO UPDATE SET auto_dispatch=excluded.auto_dispatch,paused=excluded.paused,concurrency=excluded.concurrency,budget_minutes=excluded.budget_minutes,permission_mode=excluded.permission_mode,updated_at=excluded.updated_at').run(projectId,next.autoDispatch?1:0,next.paused?1:0,next.concurrency,next.budgetMinutes,next.permissionMode,now());const said:string[]=[];if(next.autoDispatch!==cur.autoDispatch)said.push(next.autoDispatch?'turned on auto-dispatch':'turned off auto-dispatch');if(next.paused!==cur.paused)said.push(next.paused?'paused dispatch':'resumed dispatch');if(next.concurrency!==cur.concurrency)said.push(`concurrency ${next.concurrency}`);if(next.budgetMinutes!==cur.budgetMinutes)said.push(`run budget ${next.budgetMinutes} min`);if(next.permissionMode!==cur.permissionMode)said.push(`agent access ${next.permissionMode}`);if(said.length)this.log(projectId,actor,'project.scheduler',`Scheduler: ${said.join(', ')}`,null);return this.schedule(projectId)})}
 /** Leases stop two dispatchers from starting the same task. Expired leases are taken over. */
 acquireLease(projectId:string,taskId:string,holder:string,ttlMs:number,at=Date.now()):boolean{return this.tx(()=>{const r=this.db.prepare('SELECT holder,expires_at FROM leases WHERE task_id=?').get(taskId) as {holder:string;expires_at:number}|undefined;if(r&&r.holder!==holder&&Number(r.expires_at)>at)return false;this.db.prepare('INSERT INTO leases VALUES(?,?,?,?) ON CONFLICT(task_id) DO UPDATE SET holder=excluded.holder,expires_at=excluded.expires_at').run(taskId,projectId,holder,at+ttlMs);return true})}
 releaseLease(taskId:string,holder:string){this.db.prepare('DELETE FROM leases WHERE task_id=? AND holder=?').run(taskId,holder)}
 leasedTasks(projectId:string,at=Date.now()):string[]{return (this.db.prepare('SELECT task_id FROM leases WHERE project_id=? AND expires_at>?').all(projectId,at) as {task_id:string}[]).map(r=>r.task_id)}
 instructions(projectId:string):ProjectInstructions{const r=this.db.prepare('SELECT * FROM instructions WHERE project_id=? ORDER BY version DESC LIMIT 1').get(projectId) as Record<string,unknown>|undefined;return r?{version:Number(r.version),text:String(r.text),updatedAt:String(r.created_at)}:{version:0,text:'',updatedAt:null}}
 setInstructions(projectId:string,text:string,baseVersion:number,actor:Actor='user'):ProjectInstructions{if(text.length>32768||text.includes('\0'))throw Error('Instructions exceed 32,768 characters.');return this.tx(()=>{const cur=this.instructions(projectId);if(cur.version!==baseVersion)throw Error('The instructions changed since you opened them. Reload and apply your edit again.');if(cur.text===text)return cur;this.db.prepare('INSERT INTO instructions VALUES(?,?,?,?)').run(projectId,cur.version+1,text,now());this.log(projectId,actor,'project.instructions',text.trim()?`Updated project instructions to v${cur.version+1}`:'Cleared project instructions',null);return this.instructions(projectId)})}
 goalVersion(projectId:string):number{const r=this.db.prepare('SELECT MAX(version) AS v FROM goal_versions WHERE project_id=?').get(projectId) as {v:number|null};return r.v==null?1:Number(r.v)}
 /** Keeps a version history of the shared goal; the first change also records the original as v1. */
 recordGoal(projectId:string,previous:string,goal:string):number{if(previous===goal)return this.goalVersion(projectId);return this.tx(()=>{const ts=now(),has=this.db.prepare('SELECT 1 FROM goal_versions WHERE project_id=?').get(projectId);if(!has)this.db.prepare('INSERT INTO goal_versions VALUES(?,?,?,?)').run(projectId,1,previous,ts);const v=this.goalVersion(projectId)+1;this.db.prepare('INSERT INTO goal_versions VALUES(?,?,?,?)').run(projectId,v,goal,ts);return v})}
 /** Version of the Project-level context packet: bumps whenever its content hash changes. */
 packetVersion(projectId:string,content:string):number{const hash=createHash('sha256').update(content).digest('hex');return this.tx(()=>{const r=this.db.prepare('SELECT version,hash FROM context_packets WHERE project_id=? ORDER BY version DESC LIMIT 1').get(projectId) as {version:number;hash:string}|undefined;if(r?.hash===hash)return Number(r.version);const v=(r?Number(r.version):0)+1;this.db.prepare('INSERT INTO context_packets VALUES(?,?,?,?)').run(projectId,v,hash,now());this.db.prepare('DELETE FROM context_packets WHERE project_id=? AND version<?').run(projectId,v-20);return v})}
 coordinator(projectId:string):string|null{const r=this.db.prepare('SELECT chat_id FROM coordinators WHERE project_id=?').get(projectId) as {chat_id:string}|undefined;return r?.chat_id??null}
 coordinatorProject(chatId:string):string|null{const r=this.db.prepare('SELECT project_id FROM coordinators WHERE chat_id=?').get(chatId) as {project_id:string}|undefined;return r?.project_id??null}
 setCoordinator(projectId:string,chatId:string){this.db.prepare('INSERT INTO coordinators VALUES(?,?,?) ON CONFLICT(project_id) DO UPDATE SET chat_id=excluded.chat_id,created_at=excluded.created_at').run(projectId,chatId,now());this.log(projectId,'user','project.coordinator','Started the project coordinator',chatId)}
 coordinatorMarks(projectId:string):Map<string,{state:'applied'|'dismissed';error?:string}>{return new Map((this.db.prepare('SELECT key,state,error FROM coordinator_marks WHERE project_id=?').all(projectId) as {key:string;state:'applied'|'dismissed';error:string|null}[]).map(r=>[r.key,{state:r.state,...(r.error?{error:r.error}:{})}]))}
 markProposal(projectId:string,key:string,state:'applied'|'dismissed'){this.db.prepare('INSERT OR REPLACE INTO coordinator_marks VALUES(?,?,?,?,?)').run(projectId,key,state,null,now())}
 /** Removes every task, decision, activity row and suspension for a deleted Project. */
 purgeProject(projectId:string){this.tx(()=>{for(const table of ['tasks','decisions','activity','suspended_projects','attempts','schedules','leases','instructions','goal_versions','context_packets','coordinators','coordinator_marks'])this.db.prepare(`DELETE FROM ${table} WHERE project_id=?`).run(projectId)})}
 close(){this.db.close()}
}
