import { DatabaseSync } from 'node:sqlite';
import { chmodSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { Folder, Project, ProjectChatReference } from '../shared/protocol.ts';

export type TaskStatus = 'todo'|'running'|'blocked'|'implemented'|'verified';
export interface ProjectTask {id:string;projectId:string;title:string;status:TaskStatus;dependencies:string[];acceptance:string;evidence:string[];runChatId?:string;runRequestId?:string;runError?:string;revision:number;createdAt:string;updatedAt:string}
export interface ProjectDecision {id:string;projectId:string;title:string;rationale:string;author:string;scope:string;relatedTaskIds:string[];status:'active'|'superseded';supersededById:string|null;createdAt:string;updatedAt:string}
export interface ProjectActivity {id:string;projectId:string;actor:string;kind:string;summary:string;refId:string|null;createdAt:string}
export interface BoundedList<T> {items:T[];truncated:boolean}
export interface ProjectExport {schemaVersion:2;exportedAt:string;project:Project;folders:Folder[];chats:BoundedList<ProjectChatReference>;tasks:BoundedList<ProjectTask>;decisions:BoundedList<ProjectDecision>;activity:BoundedList<ProjectActivity>}

const MAX_ROWS=200, MAX_EVIDENCE=50, MAX_EVIDENCE_TOTAL=50_000, MAX_DEPS=50;
const now=()=>new Date().toISOString();
const parse=(v:unknown):string[]=>{try{const r=JSON.parse(String(v));return Array.isArray(r)&&r.every(x=>typeof x==='string')?r:[]}catch{return[]}};
function bounded<T>(rows:T[],limit:number):BoundedList<T>{return {items:rows.slice(0,limit),truncated:rows.length>limit}}
function task(r:Record<string,unknown>):ProjectTask{return {id:String(r.id),projectId:String(r.project_id),title:String(r.title),status:r.status as TaskStatus,dependencies:parse(r.dependencies),acceptance:String(r.acceptance),evidence:parse(r.evidence),...(typeof r.run_chat_id==='string'?{runChatId:r.run_chat_id}:{}),...(typeof r.run_request_id==='string'?{runRequestId:r.run_request_id}:{}),...(typeof r.run_error==='string'?{runError:r.run_error}:{}),revision:Number(r.revision),createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
function decision(r:Record<string,unknown>):ProjectDecision{return {id:String(r.id),projectId:String(r.project_id),title:String(r.title),rationale:String(r.rationale),author:String(r.author),scope:String(r.scope),relatedTaskIds:parse(r.related_task_ids),status:r.status as ProjectDecision['status'],supersededById:typeof r.superseded_by_id==='string'?r.superseded_by_id:null,createdAt:String(r.created_at),updatedAt:String(r.updated_at)}}
function activity(r:Record<string,unknown>):ProjectActivity{return {id:String(r.id),projectId:String(r.project_id),actor:String(r.actor),kind:String(r.kind),summary:String(r.summary),refId:typeof r.ref_id==='string'?r.ref_id:null,createdAt:String(r.created_at)}}
const SCHEMA=`CREATE TABLE IF NOT EXISTS tasks(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,title TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'todo',dependencies TEXT NOT NULL DEFAULT '[]',acceptance TEXT NOT NULL DEFAULT '',evidence TEXT NOT NULL DEFAULT '[]',revision INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,run_chat_id TEXT,run_request_id TEXT,run_error TEXT);CREATE INDEX IF NOT EXISTS tasks_project ON tasks(project_id,created_at);CREATE TABLE IF NOT EXISTS decisions(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,title TEXT NOT NULL,rationale TEXT NOT NULL DEFAULT '',author TEXT NOT NULL,scope TEXT NOT NULL DEFAULT '',related_task_ids TEXT NOT NULL DEFAULT '[]',status TEXT NOT NULL DEFAULT 'active',superseded_by_id TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS decisions_project ON decisions(project_id,created_at);CREATE TABLE IF NOT EXISTS activity(id TEXT PRIMARY KEY,project_id TEXT NOT NULL,actor TEXT NOT NULL,kind TEXT NOT NULL,summary TEXT NOT NULL,ref_id TEXT,created_at TEXT NOT NULL);CREATE INDEX IF NOT EXISTS activity_project ON activity(project_id,created_at);`;

export class ProjectTaskStore {
 private db:DatabaseSync;
 constructor(dataDir:string){mkdirSync(dataDir,{recursive:true,mode:0o700});const file=join(dataDir,'muster-project-tasks.sqlite');this.db=new DatabaseSync(file);chmodSync(file,0o600);this.db.exec('PRAGMA journal_mode=WAL; PRAGMA busy_timeout=3000;');this.db.exec(SCHEMA);const columns=this.db.prepare("SELECT name FROM pragma_table_info('tasks')").all() as {name:string}[];for(const [name,definition] of [['run_chat_id','TEXT'],['run_request_id','TEXT'],['run_error','TEXT']] as const)if(!columns.some(c=>c.name===name))this.db.exec(`ALTER TABLE tasks ADD COLUMN ${name} ${definition}`)}
 private tx<T>(fn:()=>T):T{this.db.exec('BEGIN IMMEDIATE');try{const v=fn();this.db.exec('COMMIT');return v}catch(e){this.db.exec('ROLLBACK');throw e}}
 private log(projectId:string,actor:string,kind:string,summary:string,refId:string|null){this.db.prepare('INSERT INTO activity VALUES(?,?,?,?,?,?,?)').run(randomUUID(),projectId,actor,kind,summary.slice(0,1024),refId,now())}
 getTask(id:string):ProjectTask|undefined{const r=this.db.prepare('SELECT * FROM tasks WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?task(r):undefined}
 getDecision(id:string):ProjectDecision|undefined{const r=this.db.prepare('SELECT * FROM decisions WHERE id=?').get(id) as Record<string,unknown>|undefined;return r?decision(r):undefined}
 assertTaskProject(projectId:string,id:string):ProjectTask{const t=this.getTask(id);if(!t)throw Error('Task not found.');if(t.projectId!==projectId)throw Error('Task belongs to a different project.');return t}
 assertDecisionProject(projectId:string,id:string):ProjectDecision{const d=this.getDecision(id);if(!d)throw Error('Decision not found.');if(d.projectId!==projectId)throw Error('Decision belongs to a different project.');return d}
 listTasks(projectId:string):BoundedList<ProjectTask>{const rows=this.db.prepare('SELECT * FROM tasks WHERE project_id=? ORDER BY created_at,id LIMIT ?').all(projectId,MAX_ROWS+1) as Record<string,unknown>[];return bounded(rows.map(task),MAX_ROWS)}
 listRunningTasks():ProjectTask[]{return (this.db.prepare("SELECT * FROM tasks WHERE status='running' ORDER BY updated_at LIMIT 1000").all() as Record<string,unknown>[]).map(task)}
 recoverUnlinkedRuns():ProjectTask[]{return this.tx(()=>{const rows=this.db.prepare("SELECT * FROM tasks WHERE status='running' AND run_request_id IS NOT NULL AND run_chat_id IS NULL LIMIT 1000").all() as Record<string,unknown>[];return rows.map(row=>{const t=task(row),reason='The app stopped before this task could be linked to its agent chat. Review the Project activity, then reopen the task before starting again.',ts=now();this.db.prepare('UPDATE tasks SET status=?,run_error=?,revision=revision+1,updated_at=? WHERE id=?').run('blocked',reason,ts,t.id);this.log(t.projectId,'main','task.run-recovered',reason,t.id);return {...t,status:'blocked',runError:reason,revision:t.revision+1,updatedAt:ts}})})}
 listDecisions(projectId:string):BoundedList<ProjectDecision>{const rows=this.db.prepare('SELECT * FROM decisions WHERE project_id=? ORDER BY created_at,id LIMIT ?').all(projectId,MAX_ROWS+1) as Record<string,unknown>[];return bounded(rows.map(decision),MAX_ROWS)}
 listActivity(projectId:string,limit=100):BoundedList<ProjectActivity>{const cap=Math.max(1,Math.min(200,Math.floor(limit)));const rows=this.db.prepare('SELECT * FROM activity WHERE project_id=? ORDER BY created_at DESC,id DESC LIMIT ?').all(projectId,cap+1) as Record<string,unknown>[];return bounded(rows.map(activity),cap)}
 private validateDeps(projectId:string,taskId:string|null,deps:string[]){if(deps.length>MAX_DEPS)throw Error('Too many dependencies (max 50).');const seen=new Set<string>();for(const depId of deps){if(seen.has(depId))throw Error('Duplicate dependency.');seen.add(depId);if(depId===taskId)throw Error('A task cannot depend on itself.');const dep=this.getTask(depId);if(!dep)throw Error(`Dependency not found: ${depId}`);if(dep.projectId!==projectId)throw Error('Dependencies must belong to this project.')}if(taskId){const visited=new Set<string>(),queue=[...deps];while(queue.length){const id=queue.pop()!;if(id===taskId)throw Error('Dependency would create a cycle.');if(visited.has(id))continue;visited.add(id);const t=this.getTask(id);if(t){if(t.projectId!==projectId)throw Error('Dependency graph crosses project boundary.');queue.push(...t.dependencies)}}}}
 createTask(i:{projectId:string;title:string;acceptance:string;dependencies:string[]}):ProjectTask{const title=i.title.trim();if(!title)throw Error('Task title required.');if(title.length>500||i.acceptance.length>4000)throw Error('Task fields are invalid or exceed their limits.');const deps=[...new Set(i.dependencies)],taskId=randomUUID();return this.tx(()=>{this.validateDeps(i.projectId,taskId,deps);const ts=now(),t:ProjectTask={id:taskId,projectId:i.projectId,title,status:'todo',dependencies:deps,acceptance:i.acceptance,evidence:[],revision:0,createdAt:ts,updatedAt:ts};this.db.prepare('INSERT INTO tasks(id,project_id,title,status,dependencies,acceptance,evidence,revision,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)').run(t.id,t.projectId,t.title,t.status,JSON.stringify(deps),t.acceptance,'[]',0,ts,ts);this.log(i.projectId,'main','task.create',`Created task: ${title}`,t.id);return t})}
 assertCanStartTask(i:{projectId:string;id:string;revision:number}):ProjectTask{const t=this.assertTaskProject(i.projectId,i.id);if(t.status==='running')throw Error('This task already has an active run. Open its linked chat.');if(t.revision!==i.revision)throw Error('Stale write — task was modified. Refresh and retry.');if(t.status!=='todo'&&t.status!=='blocked')throw Error('Reopen this task before starting another run.');for(const depId of t.dependencies){const dep=this.assertTaskProject(i.projectId,depId);if(dep.status!=='verified')throw Error(`Dependency "${dep.title}" is not yet verified.`)}return t}
 startTask(i:{projectId:string;id:string;revision:number;requestId:string;chatId:string}):ProjectTask{return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.runRequestId===i.requestId&&t.runChatId)return t;this.assertCanStartTask(i);const ts=now();this.db.prepare('UPDATE tasks SET status=?,run_chat_id=?,run_request_id=?,run_error=NULL,revision=revision+1,updated_at=? WHERE id=? AND project_id=?').run('running',i.chatId,i.requestId,ts,t.id,i.projectId);this.log(i.projectId,'main','task.run-started',`Started "${t.title}" in chat ${i.chatId}`,i.chatId);return {...t,status:'running',runChatId:i.chatId,runRequestId:i.requestId,runError:undefined,revision:t.revision+1,updatedAt:ts}})}
 failTaskStart(i:{projectId:string;id:string;requestId:string;chatId:string;reason:string}):ProjectTask|undefined{return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.runRequestId!==i.requestId||t.runChatId!==i.chatId||t.status!=='running')return undefined;const ts=now(),reason=i.reason.slice(0,2000);this.db.prepare('UPDATE tasks SET status=?,run_error=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=?').run('blocked',reason,ts,t.id,i.projectId);this.log(i.projectId,'main','task.run-failed',`Could not dispatch "${t.title}": ${reason}`,i.chatId);return {...t,status:'blocked',runError:reason,revision:t.revision+1,updatedAt:ts}})}
 settleRunForChat(chatId:string,status:'completed'|'failed'|'interrupted',error?:string):ProjectTask|undefined{return this.tx(()=>{const trow=this.db.prepare('SELECT * FROM tasks WHERE run_chat_id=? AND status=?').get(chatId,'running') as Record<string,unknown>|undefined;if(!trow)return;const t=task(trow),next=status==='completed'?'implemented':'blocked',reason=status==='completed'?null:(error||`Agent run ${status}. Open the linked chat to review or recover it.`).slice(0,2000),ts=now();this.db.prepare('UPDATE tasks SET status=?,run_error=?,revision=revision+1,updated_at=? WHERE id=? AND status=?').run(next,reason,ts,t.id,'running');this.log(t.projectId,'main',`task.run-${next}`,`Agent work for "${t.title}" ${status==='completed'?'finished':'stopped'}; review and record evidence.`,chatId);return {...t,status:next,runError:reason??undefined,revision:t.revision+1,updatedAt:ts}})}
 updateTaskStatus(i:{projectId:string;id:string;status:TaskStatus;evidence?:string[];revision:number}):ProjectTask{return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.revision!==i.revision)throw Error('Stale write — task was modified. Refresh and retry.');if(!['todo','running','blocked','implemented','verified'].includes(i.status))throw Error('Invalid task status.');if(i.status==='running')throw Error('Start this task in an agent chat; running status is set only by a real agent run.');let evidence=t.evidence;if(i.status==='verified'){const added=(i.evidence??[]).map(s=>s.trim()).filter(Boolean);if(!added.length)throw Error('Verification requires at least one evidence entry.');if(added.length>MAX_EVIDENCE||added.some(s=>s.length>2000))throw Error('Evidence exceeds the limit of 50 entries (2,000 characters each).');evidence=[...new Set([...evidence,...added])];if(evidence.length>MAX_EVIDENCE||JSON.stringify(evidence).length>MAX_EVIDENCE_TOTAL)throw Error('Evidence history is full. Remove older entries before adding more.')}const ts=now();this.db.prepare('UPDATE tasks SET status=?,evidence=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=?').run(i.status,JSON.stringify(evidence),ts,t.id,i.projectId);this.log(i.projectId,'main','task.status',`Task "${t.title}": ${t.status} → ${i.status}`,t.id);return {...t,status:i.status,evidence,revision:t.revision+1,updatedAt:ts}})}
 addEvidence(i:{projectId:string;id:string;entries:string[];revision:number}):ProjectTask{return this.tx(()=>{const t=this.assertTaskProject(i.projectId,i.id);if(t.revision!==i.revision)throw Error('Stale write — task was modified. Refresh and retry.');const added=i.entries.map(s=>s.trim()).filter(Boolean);if(!added.length||added.length>MAX_EVIDENCE||added.some(s=>s.length>2000))throw Error('Provide 1–50 evidence entries, each up to 2,000 characters.');const evidence=[...new Set([...t.evidence,...added])];if(evidence.length>MAX_EVIDENCE||JSON.stringify(evidence).length>MAX_EVIDENCE_TOTAL)throw Error('Evidence history is full.');const ts=now();this.db.prepare('UPDATE tasks SET evidence=?,revision=revision+1,updated_at=? WHERE id=? AND project_id=?').run(JSON.stringify(evidence),ts,t.id,i.projectId);this.log(i.projectId,'main','task.evidence',`Added evidence to "${t.title}"`,t.id);return {...t,evidence,revision:t.revision+1,updatedAt:ts}})}
 createDecision(i:{projectId:string;title:string;rationale:string;scope:string;relatedTaskIds:string[]}):ProjectDecision{const title=i.title.trim();if(!title||title.length>500||i.rationale.length>8000||i.scope.length>500)throw Error('Decision fields are invalid or exceed their limits.');const taskIds=[...new Set(i.relatedTaskIds)];if(taskIds.length>MAX_DEPS)throw Error('Too many related tasks.');return this.tx(()=>{for(const id of taskIds)this.assertTaskProject(i.projectId,id);const ts=now(),d:ProjectDecision={id:randomUUID(),projectId:i.projectId,title,rationale:i.rationale,author:'main',scope:i.scope,relatedTaskIds:taskIds,status:'active',supersededById:null,createdAt:ts,updatedAt:ts};this.db.prepare('INSERT INTO decisions VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(d.id,d.projectId,d.title,d.rationale,d.author,d.scope,JSON.stringify(taskIds),d.status,null,ts,ts);this.log(i.projectId,'main','decision.create',`Decision recorded: ${title}`,d.id);return d})}
 supersedeDecision(i:{projectId:string;id:string;replacementId:string}):ProjectDecision{return this.tx(()=>{const old=this.assertDecisionProject(i.projectId,i.id),replacement=this.assertDecisionProject(i.projectId,i.replacementId);if(old.id===replacement.id)throw Error('A decision cannot supersede itself.');if(old.status==='superseded')throw Error('Decision is already superseded.');if(replacement.status==='superseded')throw Error('Replacement decision is already superseded.');let cursor:ProjectDecision|undefined=replacement;const seen=new Set<string>();while(cursor){if(cursor.id===old.id)throw Error('Superseding would create a decision cycle.');if(seen.has(cursor.id))throw Error('Decision supersession chain is corrupt.');seen.add(cursor.id);cursor=cursor.supersededById?this.getDecision(cursor.supersededById):undefined;}const ts=now();this.db.prepare('UPDATE decisions SET status=?,superseded_by_id=?,updated_at=? WHERE id=? AND project_id=? AND status=?').run('superseded',replacement.id,ts,old.id,i.projectId,'active');this.log(i.projectId,'main','decision.supersede',`Decision "${old.title}" superseded by "${replacement.title}"`,old.id);return {...old,status:'superseded',supersededById:replacement.id,updatedAt:ts}})}
 exportProject(project:Project,folders:Folder[],chats:ProjectChatReference[]):ProjectExport{return {schemaVersion:2,exportedAt:now(),project,folders,chats:bounded(chats,MAX_ROWS),tasks:this.listTasks(project.id),decisions:this.listDecisions(project.id),activity:this.listActivity(project.id,200)}}
 close(){this.db.close()}
}
